"use client";
import { useEffect,useState } from "react";
import { useAuth } from "@/components/auth-provider";
import { getInventoryInsights } from "@/lib/api";
import { downloadCSV } from "@/lib/csv";
import type { InventoryInsightReport } from "@/lib/types";
const money=(v:number)=>new Intl.NumberFormat("fa-IR").format(v)+" تومان";
export default function InventoryReportPage(){
 const {session}=useAuth();const[q,setQ]=useState("");const[sort,setSort]=useState<"title"|"value"|"low_stock"|"sold_qty"|"dead_stock">("value");const[data,setData]=useState<InventoryInsightReport|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState("");
 async function load(){if(!session)return;setLoading(true);setError("");try{setData(await getInventoryInsights(session,{q,sort,limit:100}));}catch(e){setError(e instanceof Error?e.message:"گزارش موجودی آماده نشد")}finally{setLoading(false)}}
 useEffect(()=>{const t=setTimeout(()=>void load(),180);return()=>clearTimeout(t)},[session,q,sort]);
 function exportCSV(){if(!data)return;downloadCSV(`inventory-report-${new Date().toISOString().slice(0,10)}.csv`,[["کالا","SKU","برند","موجودی","رزرو","قابل فروش","بهای میانگین","ارزش موجودی","فروش ۳۰ روز","روز از آخرین فروش","کم‌موجود","راکد"],...data.items.map(x=>[x.title,x.sku||"",x.brand||"",x.on_hand,x.reserved,x.available,x.avg_unit_cost,x.inventory_value,x.sold_qty_30d,x.days_since_sale??"",x.low_stock?"بله":"خیر",x.dead_stock?"بله":"خیر"])]);}
 return <div><div className="page-head"><div><span className="eyebrow">تحلیل موجودی</span><h1>سلامت و ارزش انبار</h1><p>ارزش سرمایه خوابیده، کالاهای کم‌موجود، پرفروش و راکد.</p></div><button className="ghost-btn" onClick={exportCSV} disabled={!data?.items.length}>خروجی CSV</button></div><section className="panel operations-filter"><label className="grow">جست‌وجو<input value={q} onChange={e=>setQ(e.target.value)} placeholder="نام، SKU، برند یا OEM"/></label><label>مرتب‌سازی<select value={sort} onChange={e=>setSort(e.target.value as typeof sort)}><option value="value">بیشترین ارزش</option><option value="low_stock">کم‌موجود</option><option value="sold_qty">پرفروش ۳۰ روز</option><option value="dead_stock">کالای راکد</option><option value="title">نام کالا</option></select></label></section>{error&&<div className="error-box">{error}</div>}{loading&&!data?<div className="panel table-state">در حال محاسبه...</div>:data&&<><section className="report-kpis"><article><span>ارزش موجودی</span><strong>{money(data.summary.inventory_value)}</strong><small>{data.summary.sku_count} قلم</small></article><article><span>تعداد موجود</span><strong>{new Intl.NumberFormat("fa-IR").format(data.summary.on_hand)}</strong><small>{data.summary.reserved} واحد رزرو</small></article><article><span>کم‌موجود</span><strong>{data.summary.low_stock_count}</strong><small>نیازمند تأمین</small></article><article className={data.summary.dead_stock_count>0?"profit-negative":"profit-positive"}><span>راکد ۹۰ روزه</span><strong>{data.summary.dead_stock_count}</strong><small>سرمایه کم‌گردش</small></article></section><section className="panel history-panel"><div className="table-wrap"><table><thead><tr><th>کالا</th><th>موجود / قابل فروش</th><th>بهای میانگین</th><th>ارزش</th><th>فروش ۳۰ روز</th><th>آخرین فروش</th><th>وضعیت</th></tr></thead><tbody>{data.items.map(x=><tr key={x.product_id}><td><b>{x.title}</b><small className="block-note">{[x.sku,x.brand].filter(Boolean).join(" · ")}</small></td><td>{x.on_hand} / {x.available}</td><td>{money(x.avg_unit_cost)}</td><td>{money(x.inventory_value)}</td><td>{x.sold_qty_30d}</td><td>{x.last_sale_at?`${x.days_since_sale??0} روز قبل`:"بدون فروش"}</td><td><div className="status-stack">{x.low_stock&&<span className="reservation-status pending">کم‌موجود</span>}{x.dead_stock&&<span className="reservation-status rejected">راکد</span>}{!x.low_stock&&!x.dead_stock&&<span className="reservation-status fulfilled">عادی</span>}</div></td></tr>)}</tbody></table></div></section></>}</div>
}
