"use client";

import { useEffect, useMemo, useState } from "react";
import { useAuth } from "@/components/auth-provider";
import { assignCustomerPriceList, createPriceList, getPriceLists, getPricingSettings, getProductPricing, replaceProductPriceBreaks, savePricingSettings, searchCustomers, updatePriceList } from "@/lib/api";
import type { Customer, PriceBreak, PriceList, PricingSettings, ProductPricing } from "@/lib/types";

const money=(v:number)=>new Intl.NumberFormat("fa-IR").format(Math.round(v));

export default function PricingPage(){
 const {session}=useAuth();
 const [lists,setLists]=useState<PriceList[]>([]); const [selectedId,setSelectedId]=useState(""); const selected=useMemo(()=>lists.find(x=>x.id===selectedId),[lists,selectedId]);
 const [settings,setSettings]=useState<PricingSettings>({min_margin_bps:1000,cashier_may_override:true});
 const [products,setProducts]=useState<ProductPricing[]>([]); const [q,setQ]=useState("");
 const [customers,setCustomers]=useState<Customer[]>([]); const [customerQ,setCustomerQ]=useState("");
 const [newCode,setNewCode]=useState(""); const [newName,setNewName]=useState(""); const [selectedName,setSelectedName]=useState("");
 const [busy,setBusy]=useState(false); const [message,setMessage]=useState(""); const [error,setError]=useState("");
 async function load(){if(!session)return;const [ls,st,cs]=await Promise.all([getPriceLists(session),getPricingSettings(session),searchCustomers("",session)]);setLists(ls);setSettings(st);setCustomers(cs);setSelectedId(v=>v||ls.find(x=>x.is_default)?.id||ls[0]?.id||"")}
 useEffect(()=>{void load().catch(e=>setError(e instanceof Error?e.message:"دریافت تنظیمات قیمت ناموفق بود"))},[session]);
 useEffect(()=>{if(!session||!selectedId)return;const t=setTimeout(()=>getProductPricing(session,selectedId,q).then(setProducts).catch(e=>setError(e instanceof Error?e.message:"دریافت قیمت کالا ناموفق بود")),180);return()=>clearTimeout(t)},[session,selectedId,q]);
 useEffect(()=>{setSelectedName(selected?.name||"")},[selected?.id,selected?.name]);
 useEffect(()=>{if(!session)return;const t=setTimeout(()=>searchCustomers(customerQ,session).then(setCustomers).catch(()=>{}),180);return()=>clearTimeout(t)},[session,customerQ]);
 async function addList(){if(!session||!newCode.trim()||!newName.trim())return;setBusy(true);setError("");try{const row=await createPriceList(session,{code:newCode,name:newName});setLists(v=>[...v,row]);setSelectedId(row.id);setNewCode("");setNewName("");setMessage("لیست قیمت جدید ساخته شد.")}catch(e){setError(e instanceof Error?e.message:"ساخت لیست قیمت ناموفق بود")}finally{setBusy(false)}}
 async function toggleDefault(row:PriceList){if(!session)return;setBusy(true);setError("");try{const out=await updatePriceList(session,row.id,{name:row.name,is_default:true,active:true});setLists(v=>v.map(x=>x.id===out.id?out:{...x,is_default:false}));setMessage(`${out.name} به‌عنوان قیمت پیش‌فرض فروشگاه انتخاب شد.`)}catch(e){setError(e instanceof Error?e.message:"تغییر لیست پیش‌فرض ناموفق بود")}finally{setBusy(false)}}
 async function saveSelectedList(active=selected?.active??true){if(!session||!selected||!selectedName.trim())return;setBusy(true);setError("");try{const out=await updatePriceList(session,selected.id,{name:selectedName.trim(),is_default:selected.is_default,active});setLists(v=>{const next=v.map(x=>x.id===out.id?out:x);if(!out.active)setSelectedId(next.find(x=>x.is_default&&x.active)?.id||next.find(x=>x.active)?.id||out.id);return next});setMessage("تنظیمات لیست قیمت ذخیره شد.")}catch(e){setError(e instanceof Error?e.message:"ذخیره لیست قیمت ناموفق بود")}finally{setBusy(false)}}
 async function saveSettings(){if(!session)return;setBusy(true);setError("");try{setSettings(await savePricingSettings(session,settings));setMessage("Margin Guard و سطح دسترسی قیمت ذخیره شد.")}catch(e){setError(e instanceof Error?e.message:"ذخیره تنظیمات ناموفق بود")}finally{setBusy(false)}}
 async function saveBreaks(productId:string,breaks:PriceBreak[]){if(!session||!selectedId)return;setBusy(true);setError("");try{const out=await replaceProductPriceBreaks(session,selectedId,productId,breaks);setProducts(v=>v.map(x=>x.product_id===productId?{...x,breaks:out}:x));setMessage("قیمت و پلکان تعداد ذخیره شد.")}catch(e){setError(e instanceof Error?e.message:"ذخیره قیمت کالا ناموفق بود")}finally{setBusy(false)}}
 async function setCustomerList(c:Customer,value:string){if(!session)return;setError("");try{const out=await assignCustomerPriceList(session,c.id,value||null);setCustomers(v=>v.map(x=>x.id===c.id?out:x));setMessage(`سطح قیمت ${out.name} به‌روزرسانی شد.`)}catch(e){setError(e instanceof Error?e.message:"تخصیص لیست قیمت ناموفق بود")}}
 return <><div className="page-head"><div><span className="eyebrow">قیمت‌گذاری حرفه‌ای</span><h1>لیست قیمت و شرایط فروش</h1><p>خرده، مکانیک، همکار و عمده را مستقل تعریف کن؛ قیمت بر اساس مشتری و تعداد در صندوق خودکار انتخاب می‌شود.</p></div></div>
 {message&&<div className="success-box">{message}</div>}{error&&<div className="error-box">{error}</div>}
 <section className="pricing-grid-top">
  <article className="panel"><div className="panel-head"><div><h2>لیست‌های قیمت</h2><p>هر تعداد Tier که لازم داری بساز.</p></div></div><div className="price-list-tabs">{lists.map(l=><button key={l.id} className={`${selectedId===l.id?"active":""} ${!l.active?"inactive":""}`} onClick={()=>setSelectedId(l.id)}><div><b>{l.name}</b><small>{l.code}</small></div>{l.is_default?<span>پیش‌فرض</span>:<em onClick={e=>{e.stopPropagation();void toggleDefault(l)}}>پیش‌فرض کن</em>}</button>)}</div>{selected&&<div className="selected-price-list-settings"><input value={selectedName} onChange={e=>setSelectedName(e.target.value)} placeholder="نام لیست قیمت"/><label><input type="checkbox" checked={selected.active} disabled={selected.is_default||busy} onChange={e=>void saveSelectedList(e.target.checked)}/><span>فعال</span></label><button disabled={busy||!selectedName.trim()||selectedName.trim()===selected.name} onClick={()=>void saveSelectedList()}>ذخیره نام</button></div>}<div className="new-price-list"><input dir="ltr" value={newCode} onChange={e=>setNewCode(e.target.value)} placeholder="mechanic"/><input value={newName} onChange={e=>setNewName(e.target.value)} placeholder="مثلاً مکانیک"/><button disabled={busy} onClick={()=>void addList()}>+ ساخت لیست</button></div></article>
  <article className="panel"><div className="panel-head"><div><h2>Margin Guard</h2><p>جلوی فروش ناخواسته زیر حاشیه سود را می‌گیرد.</p></div></div><div className="pricing-settings"><label>حداقل حاشیه سود<input type="number" min="0" max="90" step="0.5" value={settings.min_margin_bps/100} onChange={e=>setSettings(v=>({...v,min_margin_bps:Math.round((Number(e.target.value)||0)*100)}))}/><span>%</span></label><label className="pricing-check"><input type="checkbox" checked={settings.cashier_may_override} onChange={e=>setSettings(v=>({...v,cashier_may_override:e.target.checked}))}/><div><b>صندوقدار بتواند قیمت را تغییر دهد</b><small>حتی در این حالت، قیمت زیر Margin Guard فقط برای Owner/Admin مجاز است.</small></div></label><button className="primary-btn" disabled={busy} onClick={()=>void saveSettings()}>ذخیره سیاست قیمت</button></div></article>
 </section>
 <section className="panel pricing-products"><div className="panel-head"><div><h2>قیمت کالاها — {selected?.name||"..."}</h2><p>برای هر کالا قیمت پایه و پلکان تعداد تعریف کن؛ مثلاً ۱ عدد، ۵ عدد، ۱۰ عدد.</p></div><input className="pricing-search" value={q} onChange={e=>setQ(e.target.value)} placeholder="جست‌وجوی کالا، SKU، برند یا OEM..."/></div><div className="pricing-product-list">{products.map(p=><ProductPriceEditor key={`${selectedId}:${p.product_id}`} row={p} disabled={busy} onSave={b=>saveBreaks(p.product_id,b)}/>)}</div></section>
 <section className="panel pricing-customers"><div className="panel-head"><div><h2>سطح قیمت مشتریان</h2><p>با انتخاب مشتری در POS، Tier او خودکار فعال می‌شود.</p></div><input className="pricing-search" value={customerQ} onChange={e=>setCustomerQ(e.target.value)} placeholder="نام یا تلفن مشتری..."/></div><div className="customer-tier-list">{customers.slice(0,40).map(c=><div key={c.id}><div><b>{c.name}</b><span>{c.phone||"بدون تلفن"}</span></div><select value={c.price_list_id||""} onChange={e=>void setCustomerList(c,e.target.value)}><option value="">قیمت پیش‌فرض</option>{lists.filter(x=>x.active).map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></div>)}</div></section>
 </>
}

function ProductPriceEditor({row,disabled,onSave}:{row:ProductPricing;disabled:boolean;onSave:(b:PriceBreak[])=>Promise<void>}){
 const [breaks,setBreaks]=useState<PriceBreak[]>(row.breaks);
 function update(index:number,patch:Partial<PriceBreak>){setBreaks(v=>v.map((x,i)=>i===index?{...x,...patch}:x))}
 function add(){const last=breaks[breaks.length-1];setBreaks(v=>[...v,{min_qty:last?Math.max(last.min_qty+1,5):1,unit_price:last?.unit_price||0}])}
 function remove(index:number){setBreaks(v=>v.filter((_,i)=>i!==index))}
 return <article className="pricing-product-row"><div className="pricing-product-title"><b>{row.title}</b><span>{row.brand||"بدون برند"} · {row.sku||"بدون SKU"}</span></div><div className="price-breaks">{breaks.map((b,i)=><div key={i}><label>از تعداد<input type="number" min="0.001" step="1" value={b.min_qty} onChange={e=>update(i,{min_qty:Number(e.target.value)||1})}/></label><label>قیمت واحد<input type="number" min="0" value={b.unit_price} onChange={e=>update(i,{unit_price:Number(e.target.value)||0})}/><small>تومان</small></label>{breaks.length>1&&<button className="remove-break" onClick={()=>remove(i)}>×</button>}</div>)}<button className="add-break" onClick={add}>+ پلکان تعداد</button></div><div className="price-break-actions"><small>{breaks.length?`شروع از ${money(breaks[0].unit_price)} تومان`:"بدون قیمت"}</small><button className="primary-btn" disabled={disabled} onClick={()=>void onSave([...breaks].sort((a,b)=>a.min_qty-b.min_qty))}>ذخیره</button></div></article>
}
