"use client";
import Link from "next/link";
import {useParams} from "next/navigation";
import {useEffect,useMemo,useState} from "react";
import {useAuth} from "@/components/auth-provider";
import {getSaleDetail} from "@/lib/api";
import {amountToPersianWords,barcodeBars} from "@/lib/print-utils";
import type {DocumentTemplateSettings,SaleDetail} from "@/lib/types";
const money=(v:number)=>new Intl.NumberFormat("fa-IR").format(Math.round(v))+" تومان";
const bool=(s:DocumentTemplateSettings,k:string,f=true)=>typeof s[k]==="boolean"?Boolean(s[k]):f;
const num=(s:DocumentTemplateSettings,k:string,f:number)=>typeof s[k]==="number"?Number(s[k]):f;
const str=(s:DocumentTemplateSettings,k:string,f="")=>typeof s[k]==="string"?String(s[k]):f;
const objText=(o:Record<string,unknown>|undefined,k:string)=>String(o?.[k]??"");
function MiniBarcode({value}:{value:string}){const bits=barcodeBars(value);return <div className="invoice-barcode">{bits.split("").map((x,i)=><i key={i} className={x==="1"?"on":""}/>)}</div>}
export default function SaleInvoice(){
 const{session}=useAuth();const params=useParams<{id:string}>();const[data,setData]=useState<SaleDetail|null>(null);const[error,setError]=useState("");
 useEffect(()=>{if(!session||!params.id)return;getSaleDetail(session,params.id).then(setData).catch(e=>setError(e instanceof Error?e.message:"فاکتور پیدا نشد"))},[session,params.id]);
 const template=useMemo(()=>{const snap=data?.document_template_snapshot||{};const raw=(snap.settings&&typeof snap.settings==="object"?snap.settings:{}) as DocumentTemplateSettings;return{paper:String(snap.paper_size||"A4"),name:String(snap.name||"قالب استاندارد"),settings:raw}},[data]);
 if(error)return <div className="error-box">{error}</div>;if(!data)return <div className="panel table-state">در حال دریافت فاکتور...</div>;
 const s:DocumentTemplateSettings={show_logo:true,show_store_name:true,show_store_address:true,show_store_phone:true,show_customer:true,show_tax_identity:true,show_sku:true,show_oem:true,show_brand:true,show_barcode:false,show_unit:true,show_discount:true,show_tax:true,show_payment:true,show_qr:true,show_signature:true,header_text:"",footer_text:"سپاس از خرید شما",terms_text:"",margin_mm:10,font_scale:100,...template.settings};
 const seller=data.seller_snapshot||{};const buyer=data.buyer_snapshot||{};const thermal=template.paper.toLowerCase().includes("80");
 return <div className="invoice-page"><div className="page-head no-print"><div><span className="eyebrow">فاکتور فروش · {template.name}</span><h1>جزئیات فروش</h1><p>{data.id}</p></div><div className="head-actions"><Link className="ghost-btn" href="/store/documents">طراحی قالب‌ها</Link>{data.invoice_mode==="official"&&<Link className="ghost-btn" href={`/store/tax/invoices/${data.id}`}>نسخه رسمی مالیاتی</Link>}<Link className="ghost-btn" href={`/store/returns?kind=sale&id=${encodeURIComponent(data.id)}`}>ثبت مرجوعی</Link><button className="primary-btn" onClick={()=>window.print()}>چاپ / PDF</button></div></div>
 <section className={`panel printable-invoice designed-sale-invoice ${thermal?"thermal-print":""}`} style={{padding:`${num(s,"margin_mm",thermal?3:10)}mm`,fontSize:`${num(s,"font_scale",100)}%`}}>
  <header className="designed-invoice-header"><div>{bool(s,"show_logo")&&(str(s,"logo_url")?<img className="invoice-logo-image" src={str(s,"logo_url")} alt="لوگو فروشگاه"/>:<div className="invoice-logo-placeholder">لوگو</div>)}{bool(s,"show_store_name")&&<h2>{objText(seller,"legal_name")||session?.storeName||"فروشگاه"}</h2>}{bool(s,"show_store_address")&&<p>{objText(seller,"address")}</p>}{bool(s,"show_store_phone")&&<small>{objText(seller,"phone")}</small>}</div><div className="designed-number"><b>{data.invoice_mode==="official"?"فاکتور رسمی فروش":"فاکتور فروش"}</b><span dir="ltr">{data.invoice_number_display||data.id.slice(0,12)}</span><small>{new Date(data.created_at).toLocaleString("fa-IR")}</small></div></header>
  {str(s,"header_text")&&<div className="designed-custom-text">{str(s,"header_text")}</div>}
  {bool(s,"show_customer")&&<div className="designed-party"><div><span>خریدار</span><b>{objText(buyer,"name")||data.customer_name||"مشتری نقدی"}</b></div>{bool(s,"show_tax_identity")&&<><div><span>شناسه ملی</span><b>{objText(buyer,"national_id")||"—"}</b></div><div><span>کد اقتصادی</span><b>{objText(buyer,"economic_code")||"—"}</b></div></>}</div>}
  <div className="table-wrap"><table className="designed-lines"><thead><tr><th>#</th><th>{str(s,"col_product","شرح کالا")}</th>{bool(s,"show_sku")&&<th>{str(s,"col_sku","SKU")}</th>}{bool(s,"show_oem")&&<th>{str(s,"col_oem","OEM")}</th>}{bool(s,"show_brand")&&<th>{str(s,"col_brand","برند")}</th>}{bool(s,"show_unit")&&<th>{str(s,"col_unit","واحد")}</th>}<th>{str(s,"col_qty","تعداد")}</th><th>{str(s,"col_unit_price","قیمت واحد")}</th>{bool(s,"show_discount")&&<th>{str(s,"col_discount","تخفیف")}</th>}{bool(s,"show_tax")&&<th>{str(s,"col_tax","مالیات")}</th>}<th>{str(s,"col_total","جمع")}</th></tr></thead><tbody>{data.items.map((x,i)=><tr key={x.id}><td>{i+1}</td><td><b>{x.title}</b>{bool(s,"show_barcode",false)&&x.barcode&&<div className="line-barcode"><MiniBarcode value={x.barcode}/><code>{x.barcode}</code></div>}</td>{bool(s,"show_sku")&&<td>{x.sku||"—"}</td>}{bool(s,"show_oem")&&<td>{x.oem_code||"—"}</td>}{bool(s,"show_brand")&&<td>{x.brand||"—"}</td>}{bool(s,"show_unit")&&<td>{x.unit_name||"واحد"}</td>}<td>{x.qty}</td><td>{money(x.unit_price||0)}</td>{bool(s,"show_discount")&&<td>{(x.discount_amount||0)>0?money(x.discount_amount||0):"—"}</td>}{bool(s,"show_tax")&&<td>{(x.tax_amount||0)>0?money(x.tax_amount||0):"—"}</td>}<td><b>{money(x.total_with_tax??x.line_total)}</b></td></tr>)}</tbody></table></div>
  <div className="designed-summary"><div><span>ناخالص</span><b>{money(data.gross_amount)}</b></div>{bool(s,"show_discount")&&<div><span>تخفیف</span><b>{money(data.discount_amount)}</b></div>}<div><span>خالص</span><b>{money(data.net_amount??data.total_amount-(data.tax_amount||0))}</b></div>{bool(s,"show_tax")&&<div><span>مالیات</span><b>{money(data.tax_amount||0)}</b></div>}<div className="grand"><span>مبلغ نهایی</span><strong>{money(data.total_amount)}</strong></div><small>{amountToPersianWords(data.total_amount)}</small></div>
  {bool(s,"show_payment")&&<div className="designed-payment"><span>پرداخت‌شده: {money(data.paid_amount)}</span><span>مانده: {money(data.due_amount)}</span></div>}
  {bool(s,"show_qr")&&<div className="invoice-qr-placeholder"><span>شناسه سند</span><code>{data.id}</code></div>}
  {str(s,"terms_text")&&<div className="designed-terms">{str(s,"terms_text")}</div>}
  {bool(s,"show_signature")&&<div className="designed-signatures"><span>مهر و امضای فروشنده</span><span>نام و امضای خریدار</span></div>}
  {str(s,"footer_text")&&<footer>{str(s,"footer_text")}</footer>}
 </section>
 <section className="panel no-print internal-sale-audit"><div className="panel-head"><div><h2>جزئیات داخلی قیمت و مرجوعی</h2><p>این بخش برای کنترل فروشگاه است و روی نسخه چاپی نمایش داده نمی‌شود.</p></div></div><div className="table-wrap"><table><thead><tr><th>کالا</th><th>تعداد</th><th>قیمت لیست</th><th>قیمت نهایی</th><th>تخفیف</th><th>کنترل قیمت</th><th>قابل مرجوع</th></tr></thead><tbody>{data.items.map(x=><tr key={x.id}><td>{x.title}</td><td>{x.qty} {x.unit_name}</td><td>{x.list_unit_price!=null?money(x.list_unit_price):"—"}</td><td>{money(x.unit_price||0)}</td><td>{money(x.discount_amount||0)}</td><td>{x.below_margin_guard?"زیر Margin Guard":x.price_override?"Override":"عادی"}{x.override_reason&&<small className="block-note">{x.override_reason}</small>}</td><td>{x.returnable_qty} {x.unit_name}</td></tr>)}</tbody></table></div></section>
 </div>;
}
