"use client";
import Link from "next/link";
import { useParams } from "next/navigation";
import { useEffect,useState } from "react";
import { useAuth } from "@/components/auth-provider";
import { getSaleDetail } from "@/lib/api";
import type { SaleDetail } from "@/lib/types";
const money=(v:number)=>new Intl.NumberFormat("fa-IR").format(v)+" تومان";
export default function SaleInvoice(){
 const {session}=useAuth();const params=useParams<{id:string}>();const[data,setData]=useState<SaleDetail|null>(null);const[error,setError]=useState("");
 useEffect(()=>{if(!session||!params.id)return;getSaleDetail(session,params.id).then(setData).catch(e=>setError(e instanceof Error?e.message:"فاکتور پیدا نشد"))},[session,params.id]);
 if(error)return <div className="error-box">{error}</div>;if(!data)return <div className="panel table-state">در حال دریافت فاکتور...</div>;
 return <div className="invoice-page"><div className="page-head no-print"><div><span className="eyebrow">فاکتور فروش</span><h1>جزئیات فروش</h1><p>{data.id}</p></div><div className="head-actions">{data.invoice_mode==="official"&&<Link className="ghost-btn" href={`/store/tax/invoices/${data.id}`}>نسخه رسمی</Link>}<Link className="ghost-btn" href={`/store/returns?kind=sale&id=${encodeURIComponent(data.id)}`}>ثبت مرجوعی</Link><button className="primary-btn" onClick={()=>window.print()}>چاپ فاکتور</button></div></div><section className="panel printable-invoice"><header className="invoice-header"><div><span className="eyebrow">فروشگاه هوشمند قطعات</span><h2>{data.invoice_mode==="official"?"فاکتور رسمی فروش":"فاکتور فروش"}</h2></div><div><b>{new Date(data.created_at).toLocaleDateString("fa-IR")}</b><small>{data.invoice_number_display||data.id}</small></div></header><div className="invoice-meta"><div><span>مشتری</span><b>{data.customer_name||"مشتری نقدی"}</b></div><div><span>وضعیت</span><b>{data.status}</b></div><div><span>ناخالص</span><b>{money(data.gross_amount)}</b></div><div><span>تخفیف</span><b>{money(data.discount_amount)}</b></div><div><span>خالص</span><b>{money(data.net_amount??(data.total_amount-(data.tax_amount||0)))}</b></div><div><span>مالیات</span><b>{money(data.tax_amount||0)}</b></div><div><span>پرداخت‌شده</span><b>{money(data.paid_amount)}</b></div><div><span>مانده</span><b>{money(data.due_amount)}</b></div></div><div className="table-wrap"><table><thead><tr><th>کالا</th><th>تعداد</th><th>قیمت لیست</th><th>قیمت نهایی</th><th>تخفیف</th><th>کنترل قیمت</th><th>خالص</th><th>مالیات</th><th>جمع</th><th>قابل مرجوع</th></tr></thead><tbody>{data.items.map(x=><tr key={x.id}><td><b>{x.title}</b></td><td>{x.qty} <small>{x.unit_name||"واحد"}</small></td><td>{x.list_unit_price!==undefined&&x.list_unit_price!==null?money(x.list_unit_price):"—"}</td><td>{money(x.unit_price||0)}</td><td>{(x.discount_amount||0)>0?money(x.discount_amount||0):"—"}</td><td><div className="invoice-pricing-audit">{x.below_margin_guard&&<span className="margin-audit-badge">زیر Margin Guard</span>}{x.price_override&&<span className="price-override-badge">Override قیمت</span>}{x.override_reason&&<small>{x.override_reason}</small>}{x.override_actor_user_id&&<small dir="ltr">actor: {x.override_actor_user_id.slice(0,8)}</small>}</div></td><td>{money(x.tax_base_amount??x.line_total)}</td><td>{(x.tax_amount||0)>0?money(x.tax_amount||0):"—"}</td><td>{money(x.total_with_tax??x.line_total)}</td><td>{x.returnable_qty} <small>{x.unit_name||""}</small></td></tr>)}</tbody></table></div><footer className="invoice-total"><span>جمع فاکتور{data.discount_amount>0&&<small className="block-note"> · تخفیف {money(data.discount_amount)}</small>}{(data.tax_amount||0)>0&&<small className="block-note"> · مالیات {money(data.tax_amount||0)}</small>}</span><strong>{money(data.total_amount)}</strong></footer></section></div>;
}
