"use client";
import { useEffect, useState } from "react";
import { useAuth } from "@/components/auth-provider";
import { getProfitLoss } from "@/lib/api";
import type { ProfitLoss } from "@/lib/types";

const money=(v:number)=>new Intl.NumberFormat("fa-IR").format(v)+" تومان";
const iso=(d:Date)=>d.toISOString().slice(0,10);
function monthStart(){const d=new Date();return iso(new Date(d.getFullYear(),d.getMonth(),1));}
export default function ReportsPage(){
 const {session}=useAuth();const [from,setFrom]=useState(monthStart());const [to,setTo]=useState(iso(new Date()));const [data,setData]=useState<ProfitLoss|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState("");
 async function load(){if(!session)return;setLoading(true);setError("");try{setData(await getProfitLoss(session,from,to));}catch(e){setError(e instanceof Error?e.message:"گزارش آماده نشد")}finally{setLoading(false)}}
 useEffect(()=>{void load()},[session,from,to]);
 return <div><div className="page-head"><div><span className="eyebrow">گزارش مدیریتی</span><h1>سود و زیان</h1><p>فروش، مرجوعی، بهای تمام‌شده و هزینه‌های عملیاتی در یک نمای ساده.</p></div><div className="report-range"><label>از<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>تا<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label></div></div>{error&&<div className="error-box">{error}</div>}{loading?<div className="panel table-state">در حال محاسبه گزارش...</div>:data&&<><section className="report-kpis"><article><span>فروش خالص</span><strong>{money(data.net_sales)}</strong><small>فروش منهای مرجوعی</small></article><article><span>سود ناخالص</span><strong>{money(data.gross_profit)}</strong><small>بعد از بهای تمام‌شده</small></article><article><span>هزینه عملیاتی</span><strong>{money(data.operating_expenses)}</strong><small>هزینه‌های ثبت‌شده</small></article><article className={data.net_profit>=0?"profit-positive":"profit-negative"}><span>سود خالص عملیاتی</span><strong>{money(data.net_profit)}</strong><small>{data.net_profit>=0?"سود":"زیان"} بازه انتخابی</small></article></section><div className="report-grid"><section className="panel pnl-panel"><div className="panel-head"><div><h2>صورت سود و زیان</h2><p>{new Date(data.from+"T00:00:00").toLocaleDateString("fa-IR")} تا {new Date(data.to+"T00:00:00").toLocaleDateString("fa-IR")}</p></div></div><div className="pnl-lines"><div><span>فروش ناخالص</span><b>{money(data.gross_sales)}</b></div><div className="subtractive"><span>مرجوعی فروش</span><b>- {money(data.sales_returns)}</b></div><div className="total"><span>فروش خالص</span><b>{money(data.net_sales)}</b></div><div><span>بهای تمام‌شده فروش</span><b>{money(data.cogs)}</b></div><div className="subtractive"><span>برگشت بهای تمام‌شده</span><b>- {money(data.cogs_reversed)}</b></div><div className="total"><span>بهای تمام‌شده خالص</span><b>{money(data.net_cogs)}</b></div><div className="highlight"><span>سود ناخالص</span><b>{money(data.gross_profit)}</b></div><div><span>هزینه‌های عملیاتی</span><b>{money(data.operating_expenses)}</b></div><div className="grand-total"><span>سود خالص عملیاتی</span><b>{money(data.net_profit)}</b></div></div></section><section className="panel expense-breakdown"><div className="panel-head"><div><h2>ترکیب هزینه‌ها</h2><p>تفکیک بر اساس دسته هزینه</p></div></div>{data.expense_breakdown.length===0?<div className="table-state">هزینه‌ای در این بازه نیست.</div>:data.expense_breakdown.map(x=><div className="expense-break-row" key={x.category_id}><span>{x.category_name}</span><b>{money(x.amount)}</b></div>)}</section></div></>}</div>
}
