"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { getInventory, postPurchase, searchProducts, searchSuppliers } from "@/lib/api";
import { useAuth } from "@/components/auth-provider";
import { SearchIcon } from "@/components/icons";
import type { InventoryStock, PaymentPart, Product, ProductUnit, PurchaseItem, Supplier } from "@/lib/types";

const money=(v:number)=>new Intl.NumberFormat("fa-IR").format(v);
const number=(v:number)=>new Intl.NumberFormat("fa-IR",{maximumFractionDigits:2}).format(v);
type PayMode="cash"|"card"|"credit"|"mixed";
const fallbackUnit=(p:Product):ProductUnit=>({id:`base-${p.id}`,code:p.unit||"pcs",name:"عدد",factor_to_base:1,barcode:p.barcode,is_base:true,allow_sale:true,allow_purchase:true,active:true});
const purchaseUnits=(p:Product)=>p.units?.filter(u=>u.active&&u.allow_purchase).length?p.units.filter(u=>u.active&&u.allow_purchase):[fallbackUnit(p)];
const basePurchaseUnit=(p:Product)=>purchaseUnits(p).find(u=>u.is_base)||purchaseUnits(p)[0];
const lineKey=(i:PurchaseItem)=>`${i.product.id}:${i.unit.id}`;

export default function PurchasesPage(){
 const {session}=useAuth(); const [query,setQuery]=useState(""); const [products,setProducts]=useState<Product[]>([]); const [inventory,setInventory]=useState<InventoryStock[]>([]); const [items,setItems]=useState<PurchaseItem[]>([]);
 const [supplierQ,setSupplierQ]=useState(""); const [suppliers,setSuppliers]=useState<Supplier[]>([]); const [supplier,setSupplier]=useState<Supplier|null>(null);
 const [method,setMethod]=useState<PayMode>("credit"); const [cashAmount,setCashAmount]=useState(0); const [cardAmount,setCardAmount]=useState(0); const [busy,setBusy]=useState(false); const [success,setSuccess]=useState(""); const [error,setError]=useState("");
 useEffect(()=>{if(!session)return;void Promise.all([searchProducts("",session),searchSuppliers("",session),getInventory(session)]).then(([p,s,inv])=>{setProducts(p);setSuppliers(s);setInventory(inv)}).catch(e=>setError(e instanceof Error?e.message:"دریافت اطلاعات خرید ناموفق بود."))},[session]);
 useEffect(()=>{if(!session)return;const t=setTimeout(()=>void searchProducts(query,session).then(setProducts).catch(()=>{}),180);return()=>clearTimeout(t)},[query,session]);
 useEffect(()=>{if(!session)return;const t=setTimeout(()=>void searchSuppliers(supplierQ,session).then(setSuppliers).catch(()=>{}),180);return()=>clearTimeout(t)},[supplierQ,session]);
 const costMap=useMemo(()=>new Map(inventory.map(x=>[x.product_id,x.avg_unit_cost])),[inventory]); const total=useMemo(()=>items.reduce((s,x)=>s+x.qty*x.unitCost,0),[items]); const totalQty=useMemo(()=>items.reduce((s,x)=>s+x.qty,0),[items]); const totalBaseQty=useMemo(()=>items.reduce((s,x)=>s+x.qty*x.unit.factor_to_base,0),[items]);
 const explicitPaid=method==="mixed"?Math.max(0,cashAmount)+Math.max(0,cardAmount):(method==="credit"?0:total); const paid=Math.min(total,explicitPaid); const due=Math.max(0,total-paid);
 function add(product:Product,preferred?:ProductUnit){const unit=preferred||basePurchaseUnit(product);setItems(prev=>{const key=`${product.id}:${unit.id}`;const found=prev.find(x=>lineKey(x)===key);if(found)return prev.map(x=>lineKey(x)===key?{...x,qty:x.qty+1}:x);const baseCost=costMap.get(product.id)||product.mockUnitCost||0;return[...prev,{product,unit,qty:1,unitCost:Math.round(baseCost*unit.factor_to_base)}]});setQuery("")}
 function update(key:string,patch:Partial<PurchaseItem>){setItems(prev=>prev.map(x=>lineKey(x)===key?{...x,...patch}:x))}
 function changeUnit(key:string,unitId:string){setItems(prev=>{const current=prev.find(x=>lineKey(x)===key);if(!current)return prev;const unit=purchaseUnits(current.product).find(u=>u.id===unitId);if(!unit)return prev;const targetKey=`${current.product.id}:${unit.id}`;if(targetKey===key)return prev;const existing=prev.find(x=>lineKey(x)===targetKey);if(existing)return prev.filter(x=>lineKey(x)!==key).map(x=>lineKey(x)===targetKey?{...x,qty:x.qty+current.qty}:x);const baseCost=costMap.get(current.product.id)||current.product.mockUnitCost||0;return prev.map(x=>lineKey(x)===key?{...x,unit,unitCost:Math.round(baseCost*unit.factor_to_base)}:x)})}
 function scanEnter(e:React.KeyboardEvent<HTMLInputElement>){if(e.key!=="Enter"||!query.trim())return;e.preventDefault();const n=query.trim().toLowerCase();for(const p of products){const unit=purchaseUnits(p).find(u=>u.barcode?.trim().toLowerCase()===n);if(unit){add(p,unit);return}if([p.barcode,p.sku,p.oem_code].filter(Boolean).some(v=>String(v).trim().toLowerCase()===n)){add(p,basePurchaseUnit(p));return}}if(products.length===1)add(products[0])}
 function choose(m:PayMode){setMethod(m);if(m!=="mixed"){setCashAmount(0);setCardAmount(0)}}
 function paymentParts():PaymentPart[]{if(method!=="mixed")return[];const parts:PaymentPart[]=[];if(cashAmount>0)parts.push({method:"cash",amount:cashAmount});if(cardAmount>0)parts.push({method:"card",amount:cardAmount});return parts}
 async function submit(){if(!session||!supplier||!items.length)return;if(items.some(x=>x.qty<=0||x.unitCost<0)){setError("تعداد و قیمت خرید ردیف‌ها را بررسی کن.");return}if(method==="mixed"&&cashAmount+cardAmount>total){setError("جمع پرداخت نقد و کارت از مبلغ خرید بیشتر است.");return}setBusy(true);setError("");setSuccess("");try{const legacy=method==="mixed"?"credit":method;const out=await postPurchase(session,supplier.id,items,legacy,method==="mixed"?paymentParts():undefined);setSuccess(`خرید ثبت شد — ${money(out.total_amount)} تومان${out.due_amount?` | بدهی ${money(out.due_amount)}`:""} — شناسه: ${out.id}`);setItems([]);setSupplier(null);setSupplierQ("");setCashAmount(0);setCardAmount(0);setInventory(await getInventory(session))}catch(e){setError(e instanceof Error?e.message:"ثبت خرید ناموفق بود.")}finally{setBusy(false)}}
 return <><div className="page-head"><div><span className="eyebrow">ورود کالا به انبار</span><h1>خرید جدید</h1><p>خرید کامل، نسیه یا ترکیبی؛ موجودی و حساب تأمین‌کننده با هم بروزرسانی می‌شوند.</p></div><div className="head-actions"><Link className="primary-btn" href="/store/products/new">+ کالای جدید</Link><Link className="ghost-btn" href="/store/purchases/history">تاریخچه خرید</Link><span className="sale-number">سند خرید جدید</span></div></div>
 <div className="purchase-layout"><section className="purchase-main"><div className="search-card"><SearchIcon/><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={scanEnter} placeholder="نام، کد، OEM یا بارکد کالا..."/><span className="scanner-hint">اسکن + Enter</span>{query&&<div className="search-results">{products.slice(0,8).map(p=>{const matched=purchaseUnits(p).find(u=>query.trim()&&u.barcode?.trim().toLowerCase()===query.trim().toLowerCase());return <button key={p.id} type="button" onClick={()=>add(p,matched)}><div><b>{p.title}</b><span>{[p.sku,p.brand,matched?`بارکد ${matched.name}`:undefined].filter(Boolean).join(" • ")}</span></div><div className="search-price"><small>{purchaseUnits(p).length>1?`${purchaseUnits(p).length} واحد خرید`:"بهای واحد پایه"}</small><strong>{money(costMap.get(p.id)||p.mockUnitCost||0)}</strong></div></button>})}{!products.length&&<div className="search-empty">کالایی پیدا نشد.</div>}</div>}</div>
 <article className="panel purchase-items"><div className="panel-head"><div><h2>اقلام خرید</h2><p>{number(items.length)} ردیف / {number(totalQty)} بسته تجاری / {number(totalBaseQty)} واحد پایه</p></div></div>{!items.length?<div className="empty-state"><b>هنوز کالایی اضافه نشده</b><span>از جست‌وجوی بالا کالا را به سند خرید اضافه کن.</span></div>:<div className="purchase-lines"><div className="purchase-line purchase-line-head"><span>کالا</span><span>تعداد</span><span>قیمت خرید واحد</span><span>جمع</span><span></span></div>{items.map(item=>{const key=lineKey(item);const units=purchaseUnits(item.product);return <div className="purchase-line multi-unit-line" key={key}><div className="line-product"><b>{item.product.title}</b><span>{item.product.sku||"بدون کد"} • بهای پایه قبلی: {money(costMap.get(item.product.id)||0)}</span><div className="line-unit-picker"><select value={item.unit.id} onChange={e=>changeUnit(key,e.target.value)}>{units.map(u=><option key={u.id} value={u.id}>{u.name}{u.is_base?" (پایه)":` × ${u.factor_to_base}`}</option>)}</select><small>{item.unit.is_base?item.unit.name:`هر ${item.unit.name} = ${number(item.unit.factor_to_base)} واحد پایه`}{item.unit.barcode?` • ${item.unit.barcode}`:""}</small></div></div><div className="qty-control"><button type="button" onClick={()=>update(key,{qty:Math.max(.001,item.qty-1)})}>−</button><input inputMode="decimal" value={item.qty} onChange={e=>update(key,{qty:Number(e.target.value)||0})}/><button type="button" onClick={()=>update(key,{qty:item.qty+1})}>+</button></div><div className="price-input wide-price"><input inputMode="numeric" value={item.unitCost} onChange={e=>update(key,{unitCost:Number(e.target.value)||0})}/><span>تومان/{item.unit.name}</span></div><strong className="line-total">{money(item.qty*item.unitCost)}</strong><button className="remove" type="button" onClick={()=>setItems(prev=>prev.filter(x=>lineKey(x)!==key))}>×</button></div>})}</div>}</article></section>
 <aside className="checkout-card purchase-checkout">{success&&<div className="success-box">{success}</div>}{error&&<div className="error-box">{error}</div>}<div><span>تأمین‌کننده</span><div className="customer-picker"><input value={supplierQ} onChange={e=>{setSupplierQ(e.target.value);if(supplier&&e.target.value!==supplier.name)setSupplier(null)}} placeholder="نام یا تلفن تأمین‌کننده"/>{supplierQ&&!supplier&&<div className="customer-results">{suppliers.slice(0,7).map(s=><button type="button" key={s.id} onClick={()=>{setSupplier(s);setSupplierQ(s.name)}}><b>{s.name}</b><span>{[s.code,s.phone].filter(Boolean).join(" • ")}</span></button>)}</div>}{supplier&&<button className="selected-customer" type="button" onClick={()=>{setSupplier(null);setSupplierQ("")}}><span>{supplier.name}</span><b>×</b></button>}</div></div><hr/>
 <div><span>روش پرداخت</span><div className="payment-grid payment-grid-4"><button className={method==="cash"?"selected":""} onClick={()=>choose("cash")}>نقد</button><button className={method==="card"?"selected":""} onClick={()=>choose("card")}>کارت</button><button className={method==="credit"?"selected":""} onClick={()=>choose("credit")}>نسیه</button><button className={method==="mixed"?"selected":""} onClick={()=>choose("mixed")}>ترکیبی</button></div></div>{method==="mixed"&&<div className="split-payment"><label>نقد<input type="number" min="0" value={cashAmount} onChange={e=>setCashAmount(Number(e.target.value)||0)}/></label><label>کارت<input type="number" min="0" value={cardAmount} onChange={e=>setCardAmount(Number(e.target.value)||0)}/></label></div>}<hr/>
 <div className="purchase-summary"><div><span>تعداد ردیف</span><b>{number(items.length)}</b></div><div><span>جمع واحد پایه</span><b>{number(totalBaseQty)}</b></div></div><div className="payment-summary"><div><span>جمع خرید</span><b>{money(total)}</b></div><div><span>پرداخت‌شده</span><b>{money(paid)}</b></div><div className={due>0?"due":""}><span>بدهی</span><b>{money(due)}</b></div></div><button className="submit-sale" disabled={busy||!supplier||!items.length} onClick={()=>void submit()}>{busy?"در حال ثبت خرید...":"ثبت خرید و ورود به انبار"}</button><small className="checkout-note">مانده پرداخت‌نشده به حساب تأمین‌کننده منتقل می‌شود.</small></aside></div></>
}
