"use client";
import Link from "next/link";
import {FormEvent,useEffect,useState} from "react";
import {useAuth} from "@/components/auth-provider";
import {addWorkshopItem,addWorkshopPayment,completeWorkshopJob,createWorkshopJob,getWorkshopJob,listMyReservations,listWorkshopJobs,workshopSummary,type ReservationLite,type WorkshopJob,type WorkshopSummary} from "@/lib/workshop-network";
const money=(v:number)=>new Intl.NumberFormat("fa-IR").format(v)+" تومان";
export default function Page(){const {ready,session,login}=useAuth();const [summary,setSummary]=useState<WorkshopSummary|null>(null);const [jobs,setJobs]=useState<WorkshopJob[]>([]);const [job,setJob]=useState<WorkshopJob|null>(null);const [reservations,setReservations]=useState<ReservationLite[]>([]);const [error,setError]=useState("");const [notice,setNotice]=useState("");
async function refresh(){if(!session)return;try{setSummary(await workshopSummary(session));setJobs(await listWorkshopJobs(session));setReservations((await listMyReservations(session)).filter(x=>x.status==="fulfilled"));if(job)setJob(await getWorkshopJob(session,job.id));}catch(e){setError(e instanceof Error?e.message:"خواندن کارگاه ناموفق بود.")}}
useEffect(()=>{if(ready&&session?.role==="mechanic")void refresh()},[ready,session]);
async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!session)return;const f=new FormData(e.currentTarget);try{const x=await createWorkshopJob(session,{vehicle_token:String(f.get("vehicle_token")||""),customer_name:s(f,"customer_name"),customer_phone:s(f,"customer_phone"),mileage:n(f,"mileage"),complaint:s(f,"complaint")});setJob(x);await refresh();setNotice("برگه کار ساخته شد.");e.currentTarget.reset()}catch(err){setError(err instanceof Error?err.message:"ساخت برگه کار ناموفق بود.")}}
async function item(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!session||!job)return;const f=new FormData(e.currentTarget);try{setJob(await addWorkshopItem(session,job.id,{item_type:String(f.get("item_type")||"service"),title:String(f.get("title")||""),qty:n(f,"qty"),unit_price:n(f,"unit_price"),reservation_id:s(f,"reservation_id"),notes:s(f,"notes")}));await refresh();setNotice("ردیف کار ثبت شد.");e.currentTarget.reset()}catch(err){setError(err instanceof Error?err.message:"ثبت ردیف ناموفق بود.")}}
async function pay(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!session||!job)return;const f=new FormData(e.currentTarget);try{setJob(await addWorkshopPayment(session,job.id,{method:String(f.get("method")||"cash"),amount:Number(f.get("amount")||0),note:s(f,"note")}));await refresh();setNotice("پرداخت ثبت شد.");e.currentTarget.reset()}catch(err){setError(err instanceof Error?err.message:"ثبت پرداخت ناموفق بود.")}}
if(!ready)return <main className="nw-page">در حال بارگذاری...</main>;if(!session)return <main className="nw-page"><button onClick={()=>void login("/mechanic/workshop")}>ورود مکانیک</button></main>;if(session.role!=="mechanic")return <main className="nw-page">این صفحه مخصوص مکانیک است.</main>;
return <main className="nw-page"><header className="nw-header"><div><span>کارگاه من</span><h1>برگه کار، اجرت، قطعه و طلب مشتری</h1><p>هر کار به دفتر همان خودرو متصل می‌ماند.</p></div><div className="nw-header-actions"><Link href="/mechanic/vehicle-notebook">دفتر خودرو</Link><Link href="/mechanic/accounts">حساب فروشگاه‌ها</Link></div></header>{error&&<div className="nw-alert error">{error}</div>}{notice&&<div className="nw-alert success">{notice}</div>}{summary&&<div className="nw-kpis"><K t="کار باز" v={String(summary.open_jobs)}/><K t="انجام‌شده ۳۰ روز" v={String(summary.completed_30_days)}/><K t="طلب از مشتری" v={money(summary.customer_receivable_amount)}/><K t="فروش ۳۰ روز" v={money(summary.revenue_30_days)}/><K t="قطعه شبکه" v={money(summary.network_part_amount_30_days)}/></div>}
<form className="nw-form-card" onSubmit={create}><h2>برگه کار جدید</h2><div className="nw-grid"><label className="wide"><span>QR / Token خودرو</span><input name="vehicle_token" required dir="ltr"/></label><label><span>نام مشتری</span><input name="customer_name"/></label><label><span>موبایل</span><input name="customer_phone"/></label><label><span>کیلومتر</span><input name="mileage" inputMode="numeric"/></label><label className="wide"><span>شرح مراجعه</span><input name="complaint"/></label></div><button className="primary">ایجاد برگه کار</button></form>
<section className="nw-columns"><div className="nw-panel"><h2>برگه‌های کار</h2><div className="nw-list">{jobs.map(x=><button className={`nw-row ${job?.id===x.id?"active":""}`} key={x.id} onClick={async()=>session&&setJob(await getWorkshopJob(session,x.id))}><div><b>{x.vehicle_label||x.plate||"خودرو"}</b><span>{x.status} · {money(x.total_amount)}</span></div><strong>{money(x.due_amount)}</strong></button>)}</div></div><div className="nw-panel">{job?<><div className="nw-panel-title"><h2>{job.vehicle_label||job.plate||"برگه کار"}</h2><span className={`status ${job.status}`}>{job.status}</span></div><div className="nw-money-strip"><span>اجرت<b>{money(job.labor_amount)}</b></span><span>قطعه<b>{money(job.parts_amount)}</b></span><span>جمع<b>{money(job.total_amount)}</b></span><span>مانده مشتری<b>{money(job.due_amount)}</b></span></div>{job.status==="open"&&<><form className="nw-inline-form" onSubmit={item}><select name="item_type"><option value="service">سرویس/اجرت</option><option value="part">قطعه</option></select><input name="title" required placeholder="تعویض تسمه تایم"/><input name="qty" placeholder="تعداد" inputMode="decimal"/><input name="unit_price" placeholder="مبلغ" inputMode="numeric"/><select name="reservation_id"><option value="">بدون خرید شبکه</option>{reservations.map(r=><option value={r.id} key={r.id}>{r.product_title} · {r.store_name}</option>)}</select><button>افزودن</button></form><form className="nw-inline-form payment" onSubmit={pay}><select name="method"><option value="cash">نقد</option><option value="card">کارت</option><option value="transfer">واریز</option><option value="credit">اعتباری</option></select><input name="amount" inputMode="numeric" required placeholder="مبلغ پرداخت"/><input name="note" placeholder="توضیح"/><button>ثبت پرداخت</button></form><button className="primary complete" onClick={async()=>{if(session&&job){setJob(await completeWorkshopJob(session,job.id));await refresh();setNotice("کار تکمیل و در دفتر خودرو ثبت شد.")}}}>تکمیل کار و ثبت در دفتر خودرو</button></>}
<div className="nw-table"><div className="nw-table-head"><span>عنوان</span><span>نوع</span><span>تعداد</span><span>مبلغ</span></div>{job.items?.map(i=><div className="nw-table-row" key={i.id}><span>{i.title}<small>{i.source_store_name||""}</small></span><span>{i.item_type}</span><span>{i.qty}</span><span>{money(i.line_total)}</span></div>)}</div></>:<div className="nw-empty">یک برگه کار را انتخاب کن.</div>}</div></section></main>}
function K({t,v}:{t:string,v:string}){return <div className="nw-kpi"><span>{t}</span><b>{v}</b></div>};function s(f:FormData,k:string){const v=String(f.get(k)||"").trim();return v||undefined};function n(f:FormData,k:string){const v=String(f.get(k)||"").trim();return v?Number(v):undefined}
