"use client";
import { useMemo, useState } from "react";
import { useAuth } from "@/components/auth-provider";
import { getPurchaseDetail, getSaleDetail, MOCK_MODE, postPurchaseReturn, postSaleReturn } from "@/lib/api";
import type { PurchaseDetail, SaleDetail } from "@/lib/types";

const money=(v:number)=>new Intl.NumberFormat("fa-IR").format(v);
type Kind="sale"|"purchase"; type Refund="cash"|"card"|"credit_balance";
const mockSale="99999999-9999-9999-9999-999999999991"; const mockPurchase="99999999-9999-9999-9999-999999999992";
export default function ReturnsPage(){
 const {session}=useAuth();const[kind,setKind]=useState<Kind>("sale");const[id,setId]=useState("");const[doc,setDoc]=useState<SaleDetail|PurchaseDetail|null>(null);const[qty,setQty]=useState<Record<string,number>>({});const[refund,setRefund]=useState<Refund>("credit_balance");const[busy,setBusy]=useState(false);const[error,setError]=useState("");const[success,setSuccess]=useState("");
 const selectedTotal=useMemo(()=>doc?.items.reduce((s,x)=>s+(qty[x.id]||0)*(kind==="sale"?(x.unit_price||0):x.unit_cost),0)||0,[doc,qty,kind]);
 async function lookup(){if(!session||!id.trim())return;setBusy(true);setError("");setSuccess("");try{const out=kind==="sale"?await getSaleDetail(session,id.trim()):await getPurchaseDetail(session,id.trim());setDoc(out);setQty(Object.fromEntries(out.items.map(x=>[x.id,0])))}catch(e){setDoc(null);setError(e instanceof Error?e.message:"سند پیدا نشد")}finally{setBusy(false)}}
 async function submit(){if(!session||!doc)return;const items=doc.items.filter(x=>(qty[x.id]||0)>0).map(x=>({source_item_id:x.id,qty:qty[x.id]}));if(!items.length){setError("حداقل یک قلم برای مرجوعی انتخاب کن.");return}setBusy(true);setError("");try{const out=kind==="sale"?await postSaleReturn(session,doc.id,items,refund):await postPurchaseReturn(session,doc.id,items,refund);setSuccess(`مرجوعی ثبت شد — ${money(out.total_amount)} تومان — شناسه: ${out.id}`);const refreshed=kind==="sale"?await getSaleDetail(session,doc.id):await getPurchaseDetail(session,doc.id);setDoc(refreshed);setQty(Object.fromEntries(refreshed.items.map(x=>[x.id,0])))}catch(e){setError(e instanceof Error?e.message:"ثبت مرجوعی ناموفق بود")}finally{setBusy(false)}}
 function switchKind(v:Kind){setKind(v);setDoc(null);setQty({});setError("");setSuccess("");setId("")}
 return <><div className="page-head"><div><span className="eyebrow">اصلاح معامله</span><h1>مرجوعی فروش و خرید</h1><p>سند اصلی را پیدا کن؛ فقط مقدار قابل مرجوعی اجازه ثبت دارد.</p></div></div>{success&&<div className="success-box">{success}</div>}{error&&<div className="error-box">{error}</div>}
 <section className="panel return-lookup"><div className="segmented"><button className={kind==="sale"?"active":""} onClick={()=>switchKind("sale")}>مرجوعی فروش</button><button className={kind==="purchase"?"active":""} onClick={()=>switchKind("purchase")}>مرجوعی خرید</button></div><div className="document-search"><input value={id} onChange={e=>setId(e.target.value)} placeholder={kind==="sale"?"شناسه فاکتور فروش":"شناسه سند خرید"}/><button className="primary-btn" onClick={()=>void lookup()} disabled={busy}>پیدا کردن سند</button></div>{MOCK_MODE&&<button className="mock-id" onClick={()=>setId(kind==="sale"?mockSale:mockPurchase)}>شناسه نمونه Mock را قرار بده</button>}</section>
 {doc&&<div className="return-layout"><section className="panel return-lines"><div className="panel-head"><div><h2>{kind==="sale"?"فاکتور فروش":"سند خرید"}</h2><p>{kind==="sale"?(doc as SaleDetail).customer_name:(doc as PurchaseDetail).supplier_name} • {doc.id}</p></div><b>{money(doc.total_amount)} تومان</b></div><div className="table-wrap"><table><thead><tr><th>کالا</th><th>تعداد اصلی</th><th>قبلاً مرجوع</th><th>قابل مرجوع</th><th>تعداد این مرجوعی</th></tr></thead><tbody>{doc.items.map(line=><tr key={line.id}><td><b>{line.title}</b><small className="block-note">{money(kind==="sale"?(line.unit_price||0):line.unit_cost)} تومان</small></td><td>{line.qty}</td><td>{line.returned_qty}</td><td>{line.returnable_qty}</td><td><input className="return-qty" type="number" min="0" max={line.returnable_qty} step="0.01" value={qty[line.id]||0} onChange={e=>setQty(v=>({...v,[line.id]:Math.min(line.returnable_qty,Math.max(0,Number(e.target.value)||0))}))}/></td></tr>)}</tbody></table></div></section><aside className="checkout-card return-checkout"><span>روش بازپرداخت / اصلاح حساب</span><div className="refund-grid"><button className={refund==="credit_balance"?"selected":""} onClick={()=>setRefund("credit_balance")}>{kind==="sale"?"کاهش حساب مشتری":"کاهش بدهی تأمین‌کننده"}</button><button className={refund==="cash"?"selected":""} onClick={()=>setRefund("cash")}>نقد</button><button className={refund==="card"?"selected":""} onClick={()=>setRefund("card")}>کارت</button></div><hr/><div className="checkout-total"><span>مبلغ مرجوعی</span><strong>{money(selectedTotal)} <small>تومان</small></strong></div><button className="submit-sale" disabled={busy||selectedTotal<=0} onClick={()=>void submit()}>{busy?"در حال ثبت...":"ثبت مرجوعی"}</button><small className="checkout-note">موجودی، حساب طرف و سند حسابداری در یک تراکنش اصلاح می‌شوند.</small></aside></div>}
 </>
}
