"use client";
import {useEffect,useState} from "react";
import {getEdgeHardwareConfig,getEdgeHardwareStatus,saveEdgeHardwareConfig,printEdgeReceipt,printEdgeLabel,openEdgeCashDrawer,chargeEdgePOS,type EdgeHardwareConfig} from "@/lib/edge";

const defaults:EdgeHardwareConfig={receipt_printer:{enabled:false,name:"",transport:"windows_spool_text",address:"",language:"text"},label_printer:{enabled:false,name:"",transport:"tcp9100",address:"",language:"zpl"},a4_printer:{enabled:false,name:"",transport:"system_file",address:"",language:"pdf"},cash_drawer:{enabled:false,auto_open:false},pos:{provider:"manual",address:"",timeout_seconds:30},auto_print_receipt:false};
export default function HardwarePage(){
 const[cfg,setCfg]=useState<EdgeHardwareConfig>(defaults);const[status,setStatus]=useState<Record<string,unknown>|null>(null);const[msg,setMsg]=useState("");const[busy,setBusy]=useState(false);
 useEffect(()=>{void Promise.all([getEdgeHardwareConfig(),getEdgeHardwareStatus()]).then(([c,s])=>{setCfg(c);setStatus(s)}).catch(()=>setStatus(null))},[]);
 async function save(){setBusy(true);setMsg("");try{setCfg(await saveEdgeHardwareConfig(cfg));setMsg("تنظیمات سخت‌افزار روی همین Store Edge ذخیره شد.")}catch(e){setMsg(e instanceof Error?e.message:"ذخیره انجام نشد")}finally{setBusy(false)}}
 async function testReceipt(){try{await printEdgeReceipt({number:"TEST-RECEIPT",payment_method:"cash",total_amount:125000,lines:[{title:"تست چاپ AutoParts",qty:1,unit_price:125000}]});setMsg("رسید تست به چاپگر ارسال شد.")}catch(e){setMsg(e instanceof Error?e.message:"چاپ تست ناموفق بود")}}
 async function testLabel(){try{await printEdgeLabel({title:"AutoParts Test",sku:"TEST-001",barcode:"626000000001",price:125000,copies:1});setMsg("لیبل تست ارسال شد.")}catch(e){setMsg(e instanceof Error?e.message:"لیبل تست ناموفق بود")}}
 async function drawer(){try{await openEdgeCashDrawer();setMsg("پالس بازشدن کشوی پول ارسال شد.")}catch(e){setMsg(e instanceof Error?e.message:"کشوی پول باز نشد")}}
 async function pos(){try{const r=await chargeEdgePOS(1000,"hardware-test");setMsg(r.approved?`POS تأیید شد: ${r.rrn||r.trace||"OK"}`:r.message||"این provider نیاز به تأیید اپراتور دارد.")}catch(e){setMsg(e instanceof Error?e.message:"تست POS ناموفق بود")}}
 const setPrinter=(key:"receipt_printer"|"label_printer"|"a4_printer",patch:Partial<EdgeHardwareConfig["receipt_printer"]>)=>setCfg(v=>({...v,[key]:{...v[key],...patch}}));
 return <><div className="page-head"><div><span className="eyebrow">صندوق و تجهیزات</span><h1>Store Hardware Bridge</h1><p>چاپگر رسید، لیبل، کشوی پول، A4 و رابط POS از طریق Store Edge روی همین کامپیوتر مدیریت می‌شوند.</p></div><span className={status?"status-pill ok":"status-pill warn"}>{status?"Agent محلی در دسترس":"Store Edge در دسترس نیست"}</span></div>{msg&&<div className="network-notice">{msg}</div>}
 <section className="hardware-grid">
 <article className="panel hardware-card"><div className="panel-head"><div><span className="panel-kicker">Receipt</span><h2>فیش‌پرینتر</h2><p>روی Windows برای فارسی، حالت Windows Driver پیشنهاد می‌شود.</p></div><label className="switch-filter"><input type="checkbox" checked={cfg.receipt_printer.enabled} onChange={e=>setPrinter("receipt_printer",{enabled:e.target.checked})}/><span>فعال</span></label></div><div className="hardware-form"><label>نام<input value={cfg.receipt_printer.name} onChange={e=>setPrinter("receipt_printer",{name:e.target.value})} placeholder="فیش‌پرینتر صندوق"/></label><label>روش اتصال<select value={cfg.receipt_printer.transport} onChange={e=>setPrinter("receipt_printer",{transport:e.target.value})}><option value="windows_spool_text">Windows Driver / Unicode</option><option value="tcp9100">TCP 9100 Raw</option><option value="windows_share">Windows Printer Share Raw</option><option value="file">File (QA — requires flag)</option></select></label><label>Printer name / address<input dir="ltr" value={cfg.receipt_printer.address} onChange={e=>setPrinter("receipt_printer",{address:e.target.value})} placeholder="EPSON TM-T20III یا 192.168.1.50:9100"/></label><label>زبان<select value={cfg.receipt_printer.language} onChange={e=>setPrinter("receipt_printer",{language:e.target.value})}><option value="text">Unicode text</option><option value="escpos">ESC/POS raw</option></select></label></div><label className="hardware-check"><input type="checkbox" checked={cfg.auto_print_receipt} onChange={e=>setCfg(v=>({...v,auto_print_receipt:e.target.checked}))}/> چاپ خودکار بعد از ثبت فروش</label><button className="ghost-btn" onClick={()=>void testReceipt()}>چاپ تست</button></article>
 <article className="panel hardware-card"><div className="panel-head"><div><span className="panel-kicker">Barcode / Label</span><h2>بارکد و لیبل</h2><p>بارکدخوان Keyboard-Wedge مستقیم در صفحه فروش کار می‌کند؛ برای لیبل ZPL می‌توان TCP 9100 داد.</p></div><label className="switch-filter"><input type="checkbox" checked={cfg.label_printer.enabled} onChange={e=>setPrinter("label_printer",{enabled:e.target.checked})}/><span>فعال</span></label></div><div className="hardware-form"><label>نام<input value={cfg.label_printer.name} onChange={e=>setPrinter("label_printer",{name:e.target.value})}/></label><label>روش اتصال<select value={cfg.label_printer.transport} onChange={e=>setPrinter("label_printer",{transport:e.target.value})}><option value="tcp9100">TCP 9100</option><option value="windows_share">Windows Share Raw</option><option value="file">File (QA — requires flag)</option></select></label><label>Address<input dir="ltr" value={cfg.label_printer.address} onChange={e=>setPrinter("label_printer",{address:e.target.value})} placeholder="192.168.1.51:9100"/></label><label>زبان<select value={cfg.label_printer.language} onChange={e=>setPrinter("label_printer",{language:e.target.value})}><option value="zpl">ZPL (^CI28)</option><option value="text">Text</option></select></label></div><button className="ghost-btn" onClick={()=>void testLabel()}>لیبل تست</button></article>
 <article className="panel hardware-card"><div className="panel-head"><div><span className="panel-kicker">Cash Drawer</span><h2>کشوی پول</h2><p>پالس ESC/POS از مسیر چاپگر رسید ارسال می‌شود؛ نیازمند transport خام است.</p></div></div><label className="hardware-check"><input type="checkbox" checked={cfg.cash_drawer.enabled} onChange={e=>setCfg(v=>({...v,cash_drawer:{...v.cash_drawer,enabled:e.target.checked}}))}/> فعال‌سازی کشوی پول</label><label className="hardware-check"><input type="checkbox" checked={cfg.cash_drawer.auto_open} onChange={e=>setCfg(v=>({...v,cash_drawer:{...v.cash_drawer,auto_open:e.target.checked}}))}/> بازشدن خودکار برای فروش نقدی</label><button className="ghost-btn" onClick={()=>void drawer()}>تست بازشدن</button></article>
 <article className="panel hardware-card"><div className="panel-head"><div><span className="panel-kicker">POS</span><h2>کارتخوان</h2><p>Bridge آماده provider است؛ درایور بانکی واقعی بر اساس مدل/PSP نصب می‌شود.</p></div></div><div className="hardware-form"><label>Provider<select value={cfg.pos.provider} onChange={e=>setCfg(v=>({...v,pos:{...v.pos,provider:e.target.value}}))}><option value="manual">Manual terminal</option><option value="tcp_json">Generic TCP JSON adapter</option><option value="mock">Mock (QA only)</option></select></label><label>Address<input dir="ltr" disabled={cfg.pos.provider!=="tcp_json"} value={cfg.pos.address} onChange={e=>setCfg(v=>({...v,pos:{...v.pos,address:e.target.value}}))} placeholder="127.0.0.1:19000"/></label></div><button className="ghost-btn" onClick={()=>void pos()}>تست POS</button></article>
 <article className="panel hardware-card"><div className="panel-head"><div><span className="panel-kicker">A4</span><h2>پرینتر فاکتور A4</h2><p>Bridge فایل PDF را به spooler سیستم تحویل می‌دهد. در Windows برنامه PDF پیش‌فرض باید Print verb داشته باشد.</p></div><label className="switch-filter"><input type="checkbox" checked={cfg.a4_printer.enabled} onChange={e=>setPrinter("a4_printer",{enabled:e.target.checked})}/><span>فعال</span></label></div><div className="hardware-form"><label>نام چاپگر<input value={cfg.a4_printer.name} onChange={e=>setPrinter("a4_printer",{name:e.target.value})}/></label><label>روش<select value={cfg.a4_printer.transport} onChange={e=>setPrinter("a4_printer",{transport:e.target.value})}><option value="system_file">System PDF spooler</option></select></label><label>Printer name (Linux lp؛ در Windows چاپگر پیش‌فرض)<input value={cfg.a4_printer.address} onChange={e=>setPrinter("a4_printer",{address:e.target.value})}/></label></div></article>
 </section><div className="hardware-save"><button className="primary-btn" disabled={busy||!status} onClick={()=>void save()}>{busy?"در حال ذخیره...":"ذخیره تنظیمات روی این صندوق"}</button></div>
 <section className="panel hardware-note"><b>نکته مهم درباره POS و فارسی</b><p>Bridge عمداً ادعا نمی‌کند همه کارتخوان‌های بانکی ایران با یک پروتکل کار می‌کنند. `tcp_json` یک adapter عمومی برای SDK/daemon شرکت PSP است؛ برای هر PSP/مدل واقعی provider جدا اضافه می‌کنیم. همچنین ESC/POS خام روی همه چاپگرها فارسی Unicode را درست چاپ نمی‌کند؛ در Windows حالت `Windows Driver / Unicode` انتخاب امن‌تری است.</p></section></>;
}
