"use client";
import { useEffect, useMemo, useState } from "react";
import Modal from "@/components/modal";
import { useAuth } from "@/components/auth-provider";
import { getExpenseCategories, getExpenses, postExpense } from "@/lib/api";
import type { Expense, ExpenseCategory } from "@/lib/types";

const money=(v:number)=>new Intl.NumberFormat("fa-IR").format(v)+" تومان";
const iso=(d:Date)=>d.toISOString().slice(0,10);
function monthStart(){const d=new Date();return iso(new Date(d.getFullYear(),d.getMonth(),1));}
export default function ExpensesPage(){
 const {session}=useAuth();const [categories,setCategories]=useState<ExpenseCategory[]>([]);const [items,setItems]=useState<Expense[]>([]);const [from,setFrom]=useState(monthStart());const [to,setTo]=useState(iso(new Date()));const [filter,setFilter]=useState("");const [open,setOpen]=useState(false);const [categoryId,setCategoryId]=useState("");const [amount,setAmount]=useState(0);const [method,setMethod]=useState<"cash"|"card">("card");const [note,setNote]=useState("");const [occurredOn,setOccurredOn]=useState(iso(new Date()));const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [success,setSuccess]=useState("");
 async function load(){if(!session)return;setLoading(true);setError("");try{const [cats,rows]=await Promise.all([getExpenseCategories(session),getExpenses(session,from,to,filter)]);setCategories(cats);setItems(rows);if(!categoryId&&cats[0])setCategoryId(cats[0].id);}catch(e){setError(e instanceof Error?e.message:"دریافت هزینه‌ها انجام نشد")}finally{setLoading(false)}}
 useEffect(()=>{void load()},[session,from,to,filter]);
 const total=useMemo(()=>items.reduce((s,x)=>s+x.amount,0),[items]);
 async function save(){if(!session||!categoryId||amount<=0)return;setBusy(true);setError("");try{await postExpense(session,{categoryId,amount,method,note,occurredOn});setSuccess("هزینه ثبت و سند حسابداری آن صادر شد.");setOpen(false);setAmount(0);setNote("");await load();}catch(e){setError(e instanceof Error?e.message:"ثبت هزینه انجام نشد")}finally{setBusy(false)}}
 return <><div className="page-head"><div><span className="eyebrow">هزینه‌های عملیاتی</span><h1>هزینه‌ها</h1><p>هزینه را ثبت کن؛ ثبت حسابداری نقد/کارت به‌صورت خودکار پشت صحنه انجام می‌شود.</p></div><div className="head-actions"><div className="account-total"><span>جمع بازه</span><b>{money(total)}</b></div><button className="primary-btn" onClick={()=>{setSuccess("");setError("");setOpen(true)}}>+ ثبت هزینه</button></div></div>
 {success&&<div className="success-box">{success}</div>}{error&&!open&&<div className="error-box">{error}</div>}
 <section className="panel expenses-panel"><div className="expenses-toolbar"><label>از<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>تا<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><label>دسته<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="">همه دسته‌ها</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label></div>
 {loading?<div className="table-state">در حال دریافت...</div>:items.length===0?<div className="table-state">در این بازه هزینه‌ای ثبت نشده است.</div>:<div className="table-wrap"><table><thead><tr><th>تاریخ</th><th>دسته</th><th>روش</th><th>توضیح</th><th>مبلغ</th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td>{new Date(x.occurred_on+"T00:00:00").toLocaleDateString("fa-IR")}</td><td><b>{x.category_name}</b></td><td><span className="pill">{x.method==="cash"?"نقد":"کارت"}</span></td><td>{x.note||"—"}</td><td><b>{money(x.amount)}</b></td></tr>)}</tbody></table></div>}</section>
 <Modal open={open} onClose={()=>setOpen(false)} title="ثبت هزینه" subtitle="سند هزینه و خروج وجه همزمان ثبت می‌شود"><div className="form-stack"><label>دسته هزینه<select value={categoryId} onChange={e=>setCategoryId(e.target.value)}>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>مبلغ<input type="number" min="1" value={amount||""} onChange={e=>setAmount(Number(e.target.value)||0)} placeholder="تومان"/></label><label>تاریخ<input type="date" value={occurredOn} onChange={e=>setOccurredOn(e.target.value)}/></label><div><span className="field-label">روش پرداخت</span><div className="payment-grid"><button className={method==="cash"?"selected":""} onClick={()=>setMethod("cash")}>نقد</button><button className={method==="card"?"selected":""} onClick={()=>setMethod("card")}>کارت</button></div></div><label>توضیح<textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="مثلاً اجاره ماه جاری"/></label>{error&&<div className="error-box">{error}</div>}</div><div className="modal-actions"><button className="ghost-btn" onClick={()=>setOpen(false)}>انصراف</button><button className="primary-btn" disabled={busy||!categoryId||amount<=0} onClick={()=>void save()}>{busy?"در حال ثبت...":"ثبت هزینه"}</button></div></Modal></>
}
