"use client";
import Link from "next/link";
import { useEffect,useMemo,useState } from "react";
import { useAuth } from "@/components/auth-provider";
import { getDashboardSummary } from "@/lib/api";
import type { DashboardSummary } from "@/lib/types";
const toman=(v:number)=>new Intl.NumberFormat("fa-IR").format(v)+" تومان";
export default function Dashboard(){
 const {session}=useAuth();const[data,setData]=useState<DashboardSummary|null>(null);const[error,setError]=useState("");
 useEffect(()=>{if(!session)return;getDashboardSummary(session).then(setData).catch(e=>setError(e instanceof Error?e.message:"داشبورد دریافت نشد"))},[session]);
 const max=useMemo(()=>Math.max(1,...(data?.sales_last_seven_days||[]).map(x=>x.amount)),[data]);
 if(error)return <div className="error-box">{error}</div>;if(!data)return <div className="panel table-state dashboard-loading"><span className="loading-dot"/>در حال آماده‌سازی داشبورد...</div>;
 return <><div className="page-head dashboard-head"><div><span className="eyebrow">مرکز عملیات امروز</span><h1>داشبورد فروشگاه</h1><p>فروش، سود، حساب‌ها، موجودی و سفارش‌های شبکه را در یک نگاه کنترل کن.</p></div><div className="head-actions"><Link className="ghost-btn" href="/store/purchases">+ خرید جدید</Link><Link className="primary-btn" href="/store/sales">+ فروش جدید</Link></div></div>
 <section className="kpi-grid phase11-kpis polished-kpis">
   <article className="kpi tone-primary"><div className="kpi-top"><span>فروش خالص امروز</span><i>↗</i></div><strong>{toman(data.net_sales_today)}</strong><small>مرجوعی: {toman(data.sales_returns_today)}</small></article>
   <article className="kpi tone-success"><div className="kpi-top"><span>سود ناخالص امروز</span><i>٪</i></div><strong>{toman(data.gross_profit_today)}</strong><small>براساس بهای میانگین</small></article>
   <article className="kpi tone-violet"><div className="kpi-top"><span>خرید امروز</span><i>↓</i></div><strong>{toman(data.purchases_today)}</strong><small><Link href="/store/purchases/history">مشاهده خریدها</Link></small></article>
   <article className="kpi tone-cyan"><div className="kpi-top"><span>طلب مشتریان</span><i>⇢</i></div><strong>{toman(data.receivables)}</strong><small>مانده حساب باز</small></article>
   <article className="kpi tone-warning"><div className="kpi-top"><span>بدهی تأمین‌کنندگان</span><i>⇠</i></div><strong>{toman(data.payables)}</strong><small>مانده قابل پرداخت</small></article>
   <article className="kpi tone-slate"><div className="kpi-top"><span>ارزش موجودی</span><i>▣</i></div><strong>{toman(data.inventory_value)}</strong><small>{data.low_stock_count} قلم کم‌موجود</small></article>
 </section>
 <section className="dashboard-grid polished-dashboard"><article className="panel wide"><div className="panel-head"><div><span className="panel-kicker">فروش</span><h2>فروش‌های اخیر</h2><p>آخرین فاکتورهای ثبت‌شده</p></div><Link className="panel-link" href="/store/sales/history">همه فروش‌ها ←</Link></div>{!data.recent_sales.length?<div className="table-state empty-soft">هنوز فروشی ثبت نشده.</div>:<div className="table-wrap"><table><thead><tr><th>مشتری</th><th>مبلغ</th><th>مانده</th><th>زمان</th><th></th></tr></thead><tbody>{data.recent_sales.map(s=><tr key={s.id}><td><div className="table-primary">{s.customer_name||"مشتری نقدی"}{s.network_source&&<small className="block-note">فروش شبکه</small>}</div></td><td className="money-cell">{toman(s.total_amount)}</td><td>{s.due_amount?<span className="status-pill warn">{toman(s.due_amount)}</span>:<span className="status-pill ok">تسویه</span>}</td><td>{new Date(s.created_at).toLocaleString("fa-IR")}</td><td><Link className="table-action" href={`/store/sales/${s.id}`}>جزئیات</Link></td></tr>)}</tbody></table></div>}</article>
 <article className="panel attention-panel"><div className="panel-head"><div><span className="panel-kicker attention">اقدام لازم</span><h2>نیازمند توجه</h2><p>موارد عملیاتی باز</p></div></div><div className="attention-list"><Link href="/store/inventory"><span><i className="attention-dot danger"/>کالاهای کم‌موجود</span><b>{data.low_stock_count}</b></Link><Link href="/store/orders"><span><i className="attention-dot info"/>رزروهای باز شبکه</span><b>{data.open_reservations}</b></Link><Link href="/store/closing"><span><i className="attention-dot success"/>کنترل صندوق روز</span><b>←</b></Link><Link href="/store/reports/inventory"><span><i className="attention-dot neutral"/>تحلیل ارزش انبار</span><b>←</b></Link></div></article>
 <article className="panel wide trend-panel"><div className="panel-head"><div><span className="panel-kicker">روند</span><h2>فروش ۷ روز اخیر</h2><p>مبلغ فروش ثبت‌شده هر روز</p></div><Link className="panel-link" href="/store/reports">سود و زیان ←</Link></div><div className="bars real-bars">{data.sales_last_seven_days.map(x=><div key={x.date} title={toman(x.amount)}><b>{x.amount?toman(x.amount):"—"}</b><span style={{height:`${Math.max(5,Math.round(x.amount/max*100))}%`}}></span><small>{new Date(x.date+"T00:00:00").toLocaleDateString("fa-IR",{weekday:"short"})}</small></div>)}</div></article>
 <article className="panel quick-panel polished-quick"><div><span className="panel-kicker">میانبر</span><h2>کارهای سریع</h2></div><Link className="quick-primary" href="/store/sales"><span>+</span><div><b>فروش جدید</b><small>ثبت فاکتور و پرداخت</small></div></Link><Link href="/store/purchases"><span>↓</span><div><b>خرید جدید</b><small>ورود کالا به انبار</small></div></Link><Link href="/store/accounts"><span>⇄</span><div><b>دریافت / پرداخت</b><small>تسویه حساب طرف‌ها</small></div></Link><Link href="/store/procurement"><span>⌁</span><div><b>تأمین از شبکه</b><small>خرید از فروشگاه همکار</small></div></Link></article></section></>;
}
