"use client";
import { useEffect, useMemo, useState } from "react";
import Modal from "@/components/modal";
import { useAuth } from "@/components/auth-provider";
import { getCustomerBalances, getPartyStatement, getSupplierBalances, postCustomerReceipt, postSupplierPayment } from "@/lib/api";
import type { PartyBalance, PartyStatement } from "@/lib/types";

const money=(v:number)=>new Intl.NumberFormat("fa-IR").format(Math.abs(v));
const entryLabel:Record<string,string>={sale:"فروش نسیه",purchase:"خرید نسیه",receipt:"دریافت",payment:"پرداخت",sale_return:"مرجوعی فروش",purchase_return:"مرجوعی خرید"};
type Tab="customers"|"suppliers";
export default function AccountsPage(){
 const {session}=useAuth();const [tab,setTab]=useState<Tab>("customers");const [customers,setCustomers]=useState<PartyBalance[]>([]);const [suppliers,setSuppliers]=useState<PartyBalance[]>([]);const [q,setQ]=useState("");const [selected,setSelected]=useState<PartyBalance|null>(null);const [statement,setStatement]=useState<PartyStatement|null>(null);const [statementLoading,setStatementLoading]=useState(false);const [amount,setAmount]=useState(0);const [method,setMethod]=useState<"cash"|"card">("card");const [note,setNote]=useState("");const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [success,setSuccess]=useState("");
 async function load(){if(!session)return;const [c,s]=await Promise.all([getCustomerBalances(session),getSupplierBalances(session)]);setCustomers(c);setSuppliers(s)}
 useEffect(()=>{void load().catch(e=>setError(e instanceof Error?e.message:"دریافت حساب‌ها ناموفق بود"))},[session]);
 const rows=useMemo(()=>{const src=tab==="customers"?customers:suppliers;const z=q.trim();return !z?src:src.filter(x=>x.name.includes(z)||(x.phone||"").includes(z)||(x.code||"").includes(z))},[tab,customers,suppliers,q]);
 const total=useMemo(()=>rows.reduce((s,x)=>s+Math.max(0,x.balance),0),[rows]);
 function open(row:PartyBalance){setSelected(row);setAmount(Math.max(0,row.balance));setNote("");setError("")}
 async function openStatement(row:PartyBalance){if(!session)return;setStatementLoading(true);setError("");try{setStatement(await getPartyStatement(session,tab==="customers"?"customer":"supplier",row.id));}catch(e){setError(e instanceof Error?e.message:"گردش حساب دریافت نشد")}finally{setStatementLoading(false)}}
 async function settle(){if(!session||!selected||amount<=0)return;setBusy(true);setError("");try{if(tab==="customers")await postCustomerReceipt(session,selected.id,amount,method,note);else await postSupplierPayment(session,selected.id,amount,method,note);setSuccess(tab==="customers"?"دریافت از مشتری ثبت شد.":"پرداخت به تأمین‌کننده ثبت شد.");setSelected(null);await load()}catch(e){setError(e instanceof Error?e.message:"ثبت تسویه ناموفق بود")}finally{setBusy(false)}}
 return <><div className="page-head"><div><span className="eyebrow">حساب اشخاص</span><h1>حساب‌ها و تسویه</h1><p>طلب مشتری‌ها و بدهی تأمین‌کننده‌ها را همراه با گردش کامل حساب مدیریت کن.</p></div><div className="account-total"><span>{tab==="customers"?"جمع طلب":"جمع بدهی"}</span><b>{money(total)} تومان</b></div></div>
 {success&&<div className="success-box">{success}</div>}{error&&!selected&&!statement&&<div className="error-box">{error}</div>}
 <section className="panel accounts-panel"><div className="accounts-toolbar"><div className="segmented"><button className={tab==="customers"?"active":""} onClick={()=>setTab("customers")}>مشتری‌ها</button><button className={tab==="suppliers"?"active":""} onClick={()=>setTab("suppliers")}>تأمین‌کننده‌ها</button></div><input value={q} onChange={e=>setQ(e.target.value)} placeholder="جست‌وجوی نام، تلفن یا کد..."/></div>
 <div className="table-wrap"><table><thead><tr><th>نام</th><th>تلفن / کد</th><th>وضعیت حساب</th><th></th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td><b>{row.name}</b></td><td>{row.phone||row.code||"—"}</td><td>{row.balance>0?<span className="balance due-balance">{tab==="customers"?"بدهکار":"طلبکار"} • {money(row.balance)} تومان</span>:row.balance<0?<span className="balance credit-balance">بستانکار • {money(row.balance)} تومان</span>:<span className="balance zero-balance">تسویه</span>}</td><td><div className="row-actions"><button onClick={()=>void openStatement(row)} disabled={statementLoading}>گردش حساب</button>{row.balance>0&&<button className="table-action" onClick={()=>open(row)}>{tab==="customers"?"دریافت پول":"پرداخت"}</button>}</div></td></tr>)}</tbody></table></div>{!rows.length&&<div className="table-state">حسابی پیدا نشد.</div>}</section>
 <Modal open={!!selected} onClose={()=>setSelected(null)} title={tab==="customers"?"دریافت از مشتری":"پرداخت به تأمین‌کننده"} subtitle={selected?.name}><div className="form-stack"><div className="settlement-balance"><span>مانده فعلی</span><b>{money(selected?.balance||0)} تومان</b></div><label>مبلغ<input type="number" min="1" max={selected?.balance||0} value={amount} onChange={e=>setAmount(Number(e.target.value)||0)}/></label><div><span className="field-label">روش</span><div className="payment-grid"><button className={method==="cash"?"selected":""} onClick={()=>setMethod("cash")}>نقد</button><button className={method==="card"?"selected":""} onClick={()=>setMethod("card")}>کارت</button></div></div><label>توضیح<textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="اختیاری"/></label>{error&&<div className="error-box">{error}</div>}</div><div className="modal-actions"><button className="ghost-btn" onClick={()=>setSelected(null)}>انصراف</button><button className="primary-btn" disabled={busy||amount<=0||amount>(selected?.balance||0)} onClick={()=>void settle()}>{busy?"در حال ثبت...":"ثبت تسویه"}</button></div></Modal>
 <Modal open={!!statement} onClose={()=>setStatement(null)} title="گردش حساب" subtitle={statement?.party_name}><>{statement&&<div className="statement-wrap"><div className="settlement-balance"><span>مانده فعلی</span><b>{money(statement.closing_balance)} تومان</b></div>{statement.items.length===0?<div className="table-state">گردشی برای این حساب ثبت نشده است.</div>:<div className="statement-list">{statement.items.map(x=><div className="statement-row" key={x.id}><div><b>{entryLabel[x.entry_type]||x.entry_type}</b><small>{new Date(x.created_at).toLocaleString("fa-IR")}</small></div><div className={x.change>=0?"statement-debit":"statement-credit"}><strong>{x.change>=0?"+":"-"} {money(x.change)}</strong><small>مانده: {money(x.balance)}</small></div></div>)}</div>}</div>}</><div className="modal-actions"><button className="primary-btn" onClick={()=>setStatement(null)}>بستن</button></div></Modal></>
}
