"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { ApiError, getDocumentTemplates, getTaxSettings, postSale, quotePricing, quoteTax, searchCustomers, searchProducts } from "@/lib/api";
import { useAuth } from "@/components/auth-provider";
import type { Customer, DocumentTemplate, InvoiceMode, PaymentPart, PricingSettings, Product, ProductUnit, SaleItem, TaxQuote, TaxSettings } from "@/lib/types";
import { SearchIcon } from "@/components/icons";
import { chargeEdgePOS, getEdgeHardwareConfig, getStoreEdgeStatus, printEdgeReceipt, queueOfflineSale } from "@/lib/edge";

const money=(v:number)=>new Intl.NumberFormat("fa-IR").format(Math.round(v));
type PayMode="cash"|"card"|"credit"|"mixed";
type DiscountMode="percent"|"amount";
const defaultPricingSettings:PricingSettings={min_margin_bps:1000,cashier_may_override:true};
const fallbackUnit=(p:Product):ProductUnit=>({id:`base-${p.id}`,code:p.unit||"pcs",name:p.unit==="pair"?"جفت":"عدد",factor_to_base:1,barcode:p.barcode,is_base:true,allow_sale:true,allow_purchase:true,active:true});
const saleUnits=(p:Product)=>p.units?.filter(u=>u.active&&u.allow_sale).length?p.units.filter(u=>u.active&&u.allow_sale):[fallbackUnit(p)];
const baseSaleUnit=(p:Product)=>saleUnits(p).find(u=>u.is_base)||saleUnits(p)[0];
const lineKey=(i:SaleItem)=>`${i.product.id}:${i.unit.id}`;
const unitHint=(u:ProductUnit)=>u.is_base?u.name:`${u.name} = ${new Intl.NumberFormat("fa-IR",{maximumFractionDigits:3}).format(u.factor_to_base)} واحد پایه`;

export default function SalesPage(){
 const {session}=useAuth();
 const [query,setQuery]=useState(""); const [results,setResults]=useState<Product[]>([]); const [items,setItems]=useState<SaleItem[]>([]);
 const [customers,setCustomers]=useState<Customer[]>([]); const [customer,setCustomer]=useState<Customer|null>(null); const [customerQ,setCustomerQ]=useState("");
 const [method,setMethod]=useState<PayMode>("card"); const [cashAmount,setCashAmount]=useState(0); const [cardAmount,setCardAmount]=useState(0);
 const [pricingSettings,setPricingSettings]=useState<PricingSettings>(defaultPricingSettings); const [activePriceList,setActivePriceList]=useState("خرده / مصرف‌کننده"); const [quoteBusy,setQuoteBusy]=useState(false);
 const [taxSettings,setTaxSettings]=useState<TaxSettings|null>(null); const [invoiceMode,setInvoiceMode]=useState<InvoiceMode>("normal"); const [documentTemplates,setDocumentTemplates]=useState<DocumentTemplate[]>([]); const [documentTemplateId,setDocumentTemplateId]=useState(""); const [taxQuote,setTaxQuote]=useState<TaxQuote|null>(null); const [taxBusy,setTaxBusy]=useState(false); const [taxError,setTaxError]=useState("");
 const [discountMode,setDiscountMode]=useState<DiscountMode>("percent"); const [discountValue,setDiscountValue]=useState(0);
 const [busy,setBusy]=useState(false); const [success,setSuccess]=useState(""); const [error,setError]=useState(""); const [edgeReady,setEdgeReady]=useState(false); const [posBusy,setPosBusy]=useState(false); const [posMessage,setPosMessage]=useState("");
 useEffect(()=>{if(session){searchProducts("",session).then(setResults);searchCustomers("",session).then(setCustomers);getTaxSettings(session).then(x=>{setTaxSettings(x);setInvoiceMode(x.default_invoice_mode||"normal")}).catch(()=>setTaxSettings(null));getDocumentTemplates(session).then(rows=>{const printable=rows.filter(x=>x.active&&(x.kind==="sales_invoice"||x.kind==="receipt_thermal"));setDocumentTemplates(printable);const preferred=printable.find(x=>x.kind==="sales_invoice"&&x.is_default)||printable[0];setDocumentTemplateId(preferred?.id||"")}).catch(()=>setDocumentTemplates([]))}},[session]);
 useEffect(()=>{void getStoreEdgeStatus().then(s=>setEdgeReady(Boolean(s.paired))).catch(()=>setEdgeReady(false))},[]);
 useEffect(()=>{if(!session)return;const t=setTimeout(()=>searchProducts(query,session).then(setResults).catch(()=>{}),180);return()=>clearTimeout(t)},[query,session]);
 useEffect(()=>{if(!session)return;const t=setTimeout(()=>searchCustomers(customerQ,session).then(setCustomers).catch(()=>{}),180);return()=>clearTimeout(t)},[customerQ,session]);
 const quoteKey=useMemo(()=>items.map(i=>`${i.product.id}:${i.unit.id}:${i.qty}`).join("|"),[items]);
 useEffect(()=>{if(!session||!items.length)return;let cancelled=false;setQuoteBusy(true);quotePricing(session,items.map(i=>({product_id:i.product.id,product_unit_id:i.unit.id,qty:i.qty})),customer?.id).then(q=>{if(cancelled)return;setPricingSettings({min_margin_bps:q.min_margin_bps,cashier_may_override:q.cashier_may_override});setActivePriceList(q.price_list_name||"خرده / مصرف‌کننده");const byId=new Map(q.items.map(x=>[`${x.product_id}:${x.product_unit_id}`,x]));setItems(prev=>prev.map(i=>{const row=byId.get(lineKey(i));if(!row)return i;return{...i,suggestedPrice:row.unit_price,minAllowedPrice:row.min_allowed_price,priceListId:row.price_list_id,priceListName:row.price_list_name||q.price_list_name,priceSource:row.price_source,unitPrice:i.manualPrice?i.unitPrice:row.unit_price};}))}).catch(()=>{}).finally(()=>{if(!cancelled)setQuoteBusy(false)});return()=>{cancelled=true}},[session,customer?.id,quoteKey]);
 const subtotal=useMemo(()=>items.reduce((s,i)=>s+i.qty*i.unitPrice,0),[items]);
 const taxKey=useMemo(()=>items.map(i=>`${i.product.id}:${i.qty}:${i.unitPrice}`).join("|"),[items]);
 useEffect(()=>{if(!session||!items.length){setTaxQuote(null);setTaxError("");return}let cancelled=false;setTaxBusy(true);setTaxError("");quoteTax(session,invoiceMode,customer?.id||null,items.map(i=>({product_id:i.product.id,amount:Math.round(i.qty*i.unitPrice)}))).then(q=>{if(!cancelled)setTaxQuote(q)}).catch(e=>{if(!cancelled){setTaxQuote(null);setTaxError(e instanceof Error?e.message:"محاسبه مالیات ناموفق بود")}}).finally(()=>{if(!cancelled)setTaxBusy(false)});return()=>{cancelled=true}},[session,invoiceMode,customer?.id,taxKey]);
 const total=taxQuote?.total_amount??subtotal;
 const suggestedTotal=useMemo(()=>items.reduce((s,i)=>s+i.qty*(i.suggestedPrice??i.unitPrice),0),[items]);
 const discountAmount=Math.max(0,suggestedTotal-subtotal);
 const explicitPaid=method==="mixed"?Math.max(0,cashAmount)+Math.max(0,cardAmount):(method==="credit"?0:total);
 const paid=Math.min(total,explicitPaid); const due=Math.max(0,total-paid);
 const canOfflineSale=invoiceMode==="normal"&&!taxQuote?.applied;
 const officialBlocked=invoiceMode==="official"&&Boolean(taxQuote&&!taxQuote.seller_ready);
 const canEditPrice=session?.role!=="cashier"||pricingSettings.cashier_may_override;
 const belowMargin=items.filter(i=>i.minAllowedPrice!==undefined&&i.unitPrice<i.minAllowedPrice);
 const missingReasons=items.filter(i=>{const changed=i.suggestedPrice!==undefined&&i.unitPrice!==i.suggestedPrice;const low=i.minAllowedPrice!==undefined&&i.unitPrice<i.minAllowedPrice;return (changed||(low&&["owner","admin"].includes(session?.role||"")))&&!i.overrideReason?.trim()});
 const marginBlocked=belowMargin.length>0&&!(["owner","admin"].includes(session?.role||""));
 function add(p:Product,preferred?:ProductUnit){const u=preferred||baseSaleUnit(p);setItems(prev=>{const key=`${p.id}:${u.id}`;const found=prev.find(i=>lineKey(i)===key);return found?prev.map(i=>lineKey(i)===key?{...i,qty:i.qty+1}:i):[...prev,{product:p,unit:u,qty:1,unitPrice:u.is_base?(p.mockPrice||0):Math.round((p.mockPrice||0)*u.factor_to_base)}]});setQuery("")}
 function update(key:string,patch:Partial<SaleItem>){setItems(prev=>prev.map(i=>lineKey(i)===key?{...i,...patch}:i))}
 function updateQty(key:string,qty:number){if(qty<=0){setItems(v=>v.filter(x=>lineKey(x)!==key));return}update(key,{qty})}
 function changeUnit(key:string,unitId:string){setItems(prev=>{const current=prev.find(i=>lineKey(i)===key);if(!current)return prev;const next=saleUnits(current.product).find(u=>u.id===unitId);if(!next)return prev;const targetKey=`${current.product.id}:${next.id}`;if(targetKey===key)return prev;const existing=prev.find(i=>lineKey(i)===targetKey);if(existing)return prev.filter(i=>lineKey(i)!==key).map(i=>lineKey(i)===targetKey?{...i,qty:i.qty+current.qty}:i);return prev.map(i=>lineKey(i)===key?{...i,unit:next,unitPrice:0,manualPrice:false,overrideReason:"",lineDiscountAmount:0,suggestedPrice:undefined,minAllowedPrice:undefined}:i)})}
 function setManualPrice(key:string,unitPrice:number){const value=Math.max(0,unitPrice||0);setItems(prev=>prev.map(i=>{if(lineKey(i)!==key)return i;const reset=i.suggestedPrice!==undefined&&value===i.suggestedPrice;return{...i,unitPrice:value,manualPrice:!reset,overrideReason:reset?"":i.overrideReason,lineDiscountAmount:reset?0:i.lineDiscountAmount}}))}
 function applyLineDiscount(key:string,pct:number){setItems(prev=>prev.map(i=>{if(lineKey(i)!==key)return i;const base=i.suggestedPrice??i.unitPrice;return{...i,unitPrice:Math.max(0,Math.round(base*(1-pct/100))),manualPrice:true,overrideReason:`تخفیف ${pct}٪`}}))}
 function applyLineAmountDiscount(key:string,amount:number){setItems(prev=>prev.map(i=>{if(lineKey(i)!==key)return i;const base=i.suggestedPrice??i.unitPrice;const gross=Math.max(0,base*i.qty);const applied=Math.max(0,Math.min(gross,amount||0));const unit=i.qty>0?Math.max(0,Math.round((gross-applied)/i.qty)):base;return{...i,unitPrice:unit,manualPrice:applied>0,overrideReason:applied>0?`تخفیف خط ${money(applied)} تومان`:""}}))}
 function chooseCustomer(c:Customer|null){setCustomer(c);setCustomerQ("");setDiscountValue(0);setItems(prev=>prev.map(i=>({...i,manualPrice:false,overrideReason:"",lineDiscountAmount:0})))}
 function applyInvoiceDiscount(){if(!items.length)return;const gross=items.reduce((s,i)=>s+i.qty*(i.suggestedPrice??i.unitPrice),0);if(gross<=0)return;let ratio=0;let reason="";if(discountMode==="percent"){ratio=Math.max(0,Math.min(100,discountValue))/100;reason=`تخفیف فاکتور ${Math.max(0,Math.min(100,discountValue))}٪`;}else{const amount=Math.max(0,Math.min(gross,discountValue));ratio=amount/gross;reason=`تخفیف فاکتور ${money(amount)} تومان`;}setItems(prev=>prev.map(i=>{const base=i.suggestedPrice??i.unitPrice;return{...i,unitPrice:Math.max(0,Math.round(base*(1-ratio))),manualPrice:ratio>0,overrideReason:ratio>0?reason:""}}))}
 function choose(m:PayMode){setMethod(m); if(m!=="mixed"){setCashAmount(0);setCardAmount(0)}}
 function paymentParts():PaymentPart[]{if(method!=="mixed")return[];const parts:PaymentPart[]=[];if(cashAmount>0)parts.push({method:"cash",amount:cashAmount});if(cardAmount>0)parts.push({method:"card",amount:cardAmount});return parts}
 function scanEnter(e:React.KeyboardEvent<HTMLInputElement>){if(e.key!=="Enter"||!query.trim())return;e.preventDefault();const n=query.trim().toLowerCase();for(const p of results){const unit=saleUnits(p).find(u=>u.barcode?.trim().toLowerCase()===n);if(unit){add(p,unit);return}if([p.barcode,p.sku,p.oem_code].filter(Boolean).some(v=>String(v).trim().toLowerCase()===n)){add(p,baseSaleUnit(p));return}}if(results.length===1)add(results[0])}
 async function maybePrintReceipt(number:string,payment:string,saleItems:SaleItem[],amount:number){try{const hw=await getEdgeHardwareConfig();if(!hw.auto_print_receipt||!hw.receipt_printer.enabled)return;await printEdgeReceipt({number,payment_method:payment,total_amount:amount,lines:saleItems.map(x=>({title:`${x.product.title} (${x.unit.name})`,qty:x.qty,unit_price:x.unitPrice}))})}catch{/* printing must never roll back a posted sale */}}
 async function sendToPOS(){if(total<=0)return;setPosBusy(true);setPosMessage("");try{const out=await chargeEdgePOS(total,crypto.randomUUID());setPosMessage(out.approved?`✓ کارتخوان تأیید کرد${out.rrn?` — RRN: ${out.rrn}`:""}`:out.message||"مبلغ به کارتخوان ارسال نشد؛ پرداخت را روی ترمینال انجام بده.")}catch(e){setPosMessage(e instanceof Error?e.message:"ارتباط با کارتخوان ناموفق بود")}finally{setPosBusy(false)}}
 async function submit(){if(!session||!items.length)return;if(taxBusy||taxError){setError(taxError||"محاسبه مالیات هنوز کامل نشده است.");return}if(officialBlocked){setError("برای صدور فاکتور رسمی، اطلاعات هویتی فروشگاه در تنظیمات مالیاتی کامل نیست.");return}if(missingReasons.length){setError("برای تغییر قیمت یا تأیید فروش زیر Margin Guard، دلیل را روی هر قلم وارد کن.");return}if(marginBlocked){setError(`قیمت ${belowMargin[0].product.title} زیر حداقل حاشیه سود مجاز است. فقط مالک/مدیر می‌تواند این فروش را Override کند.`);return}if(method==="mixed"&&cashAmount+cardAmount>total){setError("جمع پرداخت نقد و کارت از مبلغ فاکتور بیشتر است.");return}if(due>0&&!customer){setError("برای مانده نسیه باید مشتری انتخاب شود.");return}setBusy(true);setError("");setSuccess("");try{const legacy=method==="mixed"?"credit":method;const parts=method==="mixed"?paymentParts():undefined;const out=await postSale(session,items,customer?.id||null,legacy,parts,invoiceMode,documentTemplateId||undefined);void maybePrintReceipt(out.id,method,items,out.total_amount);setSuccess(`فروش ثبت شد${out.invoice_number_display?` — فاکتور رسمی ${out.invoice_number_display}`:""} — ${money(out.total_amount)} تومان${taxQuote?.tax_amount?` | مالیات ${money(taxQuote.tax_amount)}`:""}${discountAmount?` | تخفیف ${money(discountAmount)}`:""}${out.due_amount?` | مانده ${money(out.due_amount)}`:""} — شناسه: ${out.id}`);setItems([]);setCustomer(null);setCashAmount(0);setCardAmount(0);setDiscountValue(0)}catch(e){const offlineFailure=!navigator.onLine||e instanceof TypeError||(e instanceof ApiError&&e.status>=500);if(offlineFailure&&canOfflineSale&&(method==="cash"||method==="card")&&due===0){try{const st=await getStoreEdgeStatus();if(!st.paired)throw new Error("Store Edge روی این صندوق pair نشده است.");const local=await queueOfflineSale(items,method,customer?.id,documentTemplateId||undefined);setEdgeReady(true);setSuccess(`اینترنت/سرور در دسترس نبود؛ فروش با شماره ${local.local_number} روی Store Edge ذخیره شد و بعداً همگام می‌شود.`);setItems([]);setCustomer(null);setCashAmount(0);setCardAmount(0);setDiscountValue(0);return}catch(edgeErr){setError(`${e instanceof Error?e.message:"سرور در دسترس نیست"} — ذخیره آفلاین هم انجام نشد: ${edgeErr instanceof Error?edgeErr.message:"Store Edge در دسترس نیست"}`)}}else if(offlineFailure&&!canOfflineSale){setError(`${e instanceof Error?e.message:"سرور در دسترس نیست"} — فاکتور رسمی/مالیاتی برای حفظ شماره و snapshot مالیاتی فقط آنلاین ثبت می‌شود.`)}else{setError(e instanceof Error?e.message:"ثبت فروش ناموفق بود")}}finally{setBusy(false)}}
 return <><div className="page-head"><div><span className="eyebrow">صندوق فروش</span><h1>فروش جدید</h1><p>قیمت مشتری، پلکان تعداد، Margin Guard و مالیات فاکتور به‌صورت خودکار محاسبه می‌شود.</p></div><div className="head-actions"><Link className="ghost-btn" href="/store/pricing">مدیریت قیمت‌ها</Link><Link className="ghost-btn" href="/store/sales/history">تاریخچه فروش</Link><div className="sale-number">فاکتور جدید</div></div></div>
 {edgeReady&&<div className="offline-ready-strip"><span>● Store Edge آماده</span><small>{canOfflineSale?"فروش عادیِ بدون مالیات در قطع اینترنت قابل ذخیره است.":"فاکتور مالیاتی/رسمی برای حفظ شماره و snapshot فقط آنلاین ثبت می‌شود."}</small><Link href="/store/edge">مدیریت</Link></div>}
 {success&&<div className="success-box">{success}</div>}{error&&<div className="error-box page-error">{error}</div>}{taxError&&<div className="error-box page-error">خطای مالیات: {taxError}</div>}
 <div className="pricing-context-strip"><div><span>لیست قیمت فعال</span><b>{quoteBusy?"در حال محاسبه...":activePriceList}</b></div><div><span>حداقل حاشیه سود</span><b>{(pricingSettings.min_margin_bps/100).toLocaleString("fa-IR")}%</b></div>{customer?.price_list_name&&<div><span>سطح مشتری</span><b>{customer.price_list_name}</b></div>}{discountAmount>0&&<div className="discounted"><span>تخفیف فعلی</span><b>{money(discountAmount)} تومان</b></div>}</div>
 <div className="sale-layout"><section className="sale-main">
   <div className="search-card"><SearchIcon/><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={scanEnter} placeholder="نام، کد، OEM یا بارکد کالا..."/><span className="scanner-hint">بارکدخوان: اسکن + Enter</span>{query&&<div className="search-results">{results.slice(0,7).map(p=>{const matched=saleUnits(p).find(u=>query.trim()&&u.barcode?.trim().toLowerCase()===query.trim().toLowerCase());return <button key={p.id} onClick={()=>add(p,matched)}><div><b>{p.title}</b><span>{p.brand||"بدون برند"} · {p.sku||"بدون کد"}{matched?` · بارکد ${matched.name}`:""}</span></div><div>{p.mockPrice?<strong>{money(p.mockPrice)}</strong>:<strong>افزودن</strong>}<small>{saleUnits(p).length>1?`${saleUnits(p).length} واحد فروش`:`واحد: ${baseSaleUnit(p).name}`}</small></div></button>})}</div>}</div>
   <article className="panel sale-items"><div className="panel-head"><div><h2>اقلام فاکتور</h2><p>{items.length?`${items.length} قلم انتخاب شده`:"هنوز کالایی اضافه نشده"}</p></div></div>{!items.length?<div className="empty-state">برای شروع، نام قطعه را در جست‌وجوی بالا بنویس.</div>:<div className="sale-lines">{items.map(i=>{const key=lineKey(i);const changed=i.suggestedPrice!==undefined&&i.unitPrice!==i.suggestedPrice;const low=i.minAllowedPrice!==undefined&&i.unitPrice<i.minAllowedPrice;const units=saleUnits(i.product);return <div className={`sale-line pricing-sale-line multi-unit-line ${low?"margin-low":""}`} key={key}><div className="line-product"><b>{i.product.title}</b><span>{i.product.brand} · {i.product.sku}</span><div className="line-unit-picker"><select value={i.unit.id} onChange={e=>changeUnit(key,e.target.value)}>{units.map(u=><option key={u.id} value={u.id}>{u.name}{u.is_base?" (پایه)":` × ${u.factor_to_base}`}</option>)}</select><small>{unitHint(i.unit)}{i.unit.barcode?` · بارکد ${i.unit.barcode}`:""}</small></div><small className="line-pricing-meta">{i.priceListName||activePriceList}{i.suggestedPrice!==undefined?` · قیمت ${i.unit.name} ${money(i.suggestedPrice)}`:""}{i.minAllowedPrice!==undefined?` · حداقل ${money(i.minAllowedPrice)}`:""}</small>{(changed||low)&&<div className="override-reason"><input value={i.overrideReason||""} onChange={e=>update(key,{overrideReason:e.target.value})} placeholder={low&&!changed?"دلیل تأیید فروش زیر Margin Guard...":"دلیل تغییر قیمت..."}/></div>}</div><div className="qty-control"><button onClick={()=>updateQty(key,i.qty-1)}>−</button><input value={i.qty} type="number" min="0.001" step="0.001" onChange={e=>updateQty(key,Number(e.target.value))}/><button onClick={()=>updateQty(key,i.qty+1)}>+</button></div><div className="price-stack"><label className="price-input"><input disabled={!canEditPrice} value={i.unitPrice} type="number" min="0" onChange={e=>setManualPrice(key,Number(e.target.value))}/><span>تومان/{i.unit.name}</span></label>{canEditPrice&&i.suggestedPrice!==undefined&&<div className="quick-discounts"><button onClick={()=>applyLineDiscount(key,5)}>۵٪</button><button onClick={()=>applyLineDiscount(key,10)}>۱۰٪</button><input className="line-discount-amount" type="number" min="0" value={i.lineDiscountAmount||""} onChange={e=>update(key,{lineDiscountAmount:Number(e.target.value)||0})} placeholder="مبلغ"/><button onClick={()=>applyLineAmountDiscount(key,i.lineDiscountAmount||0)}>مبلغی</button><button onClick={()=>update(key,{unitPrice:i.suggestedPrice,manualPrice:false,overrideReason:"",lineDiscountAmount:0})}>ریست</button></div>}</div><strong className="line-total">{money(i.qty*i.unitPrice)}</strong><button className="remove" onClick={()=>setItems(v=>v.filter(x=>lineKey(x)!==key))}>×</button>{low&&<div className="margin-warning">⚠ زیر حداقل حاشیه سود{["owner","admin"].includes(session?.role||"")?" — با دلیل Override قابل ثبت است":" — نیاز به مالک/مدیر دارد"}</div>}</div>})}</div>}</article>
 </section><aside className="checkout-card"><div><span>مشتری</span><div className="customer-picker"><input value={customerQ} onChange={e=>setCustomerQ(e.target.value)} placeholder={customer?customer.name:"مشتری را جست‌وجو کن..."}/>{customerQ&&<div className="customer-results">{customers.slice(0,6).map(c=><button key={c.id} onClick={()=>chooseCustomer(c)}><b>{c.name}</b><span>{c.phone||""}{c.price_list_name?` · ${c.price_list_name}`:""}</span></button>)}</div>}</div>{customer&&<button className="selected-customer" onClick={()=>chooseCustomer(null)}><span><b>{customer.name}</b><small>{customer.price_list_name||"قیمت پیش‌فرض"}</small></span><span>×</span></button>}</div><hr/>
 <div className="invoice-mode-box"><span>نوع فاکتور</span><div className="invoice-mode-grid"><button type="button" onClick={()=>setInvoiceMode("normal")} className={invoiceMode==="normal"?"selected":""}>عادی</button><button type="button" onClick={()=>setInvoiceMode("official")} className={invoiceMode==="official"?"selected":""}>رسمی</button></div>{documentTemplates.length>0&&<label className="sale-template-picker">قالب چاپ<select value={documentTemplateId} onChange={e=>setDocumentTemplateId(e.target.value)}>{documentTemplates.map(x=><option key={x.id} value={x.id}>{x.name} · {x.paper_size}</option>)}</select></label>}<small className="checkout-note align-right">{taxBusy?"در حال محاسبه مالیات...":taxQuote?.applied?`${taxQuote.calculation_mode==="inclusive"?"مالیات داخل قیمت":"مالیات افزوده به قیمت"} · ${money(taxQuote.tax_amount)} تومان`:taxSettings?.tax_enabled?"برای این نوع فاکتور مالیات اعمال نمی‌شود.":"مالیات فروشگاه هنوز فعال نشده است."}</small>{taxQuote?.warnings?.map((w,i)=><small key={i} className="tax-warning">⚠ {w}</small>)}</div><hr/>
 <div><span>تخفیف کل فاکتور</span><div className="invoice-discount"><select value={discountMode} onChange={e=>setDiscountMode(e.target.value as DiscountMode)}><option value="percent">درصد</option><option value="amount">مبلغ</option></select><input type="number" min="0" value={discountValue} onChange={e=>setDiscountValue(Number(e.target.value)||0)}/><button onClick={applyInvoiceDiscount} disabled={!canEditPrice}>اعمال</button></div><small className="checkout-note align-right">تخفیف روی قیمت واحد اقلام توزیع و برای Audit ذخیره می‌شود.</small></div><hr/>
 <div><span>روش پرداخت</span><div className="payment-grid payment-grid-4"><button onClick={()=>choose("cash")} className={method==="cash"?"selected":""}>نقد</button><button onClick={()=>choose("card")} className={method==="card"?"selected":""}>کارت</button><button onClick={()=>choose("credit")} className={method==="credit"?"selected":""}>نسیه</button><button onClick={()=>choose("mixed")} className={method==="mixed"?"selected":""}>ترکیبی</button></div></div>
 {method==="card"&&edgeReady&&<div className="pos-bridge-box"><button type="button" className="ghost-btn" disabled={posBusy||total<=0} onClick={()=>void sendToPOS()}>{posBusy?"در حال ارتباط...":"ارسال مبلغ به کارتخوان"}</button>{posMessage&&<small>{posMessage}</small>}</div>}
 {method==="mixed"&&<div className="split-payment"><label>نقد<input type="number" min="0" value={cashAmount} onChange={e=>setCashAmount(Number(e.target.value)||0)}/></label><label>کارت<input type="number" min="0" value={cardAmount} onChange={e=>setCardAmount(Number(e.target.value)||0)}/></label></div>}
 <hr/><div className="payment-summary"><div><span>جمع قبل تخفیف</span><b>{money(suggestedTotal)}</b></div>{discountAmount>0&&<div className="discount-row"><span>تخفیف</span><b>− {money(discountAmount)}</b></div>}{taxQuote?.applied&&<><div><span>خالص مشمول/معاف</span><b>{money(taxQuote.net_amount)}</b></div><div className="tax-row"><span>مالیات / عوارض</span><b>+ {money(taxQuote.tax_amount)}</b></div></>}<div><span>جمع نهایی فاکتور</span><b>{money(total)}</b></div><div><span>پرداخت‌شده</span><b>{money(paid)}</b></div><div className={due>0?"due":""}><span>مانده حساب</span><b>{money(due)}</b></div></div>
 <button className="submit-sale" onClick={submit} disabled={!items.length||busy||quoteBusy||taxBusy||Boolean(taxError)||officialBlocked||marginBlocked||missingReasons.length>0}>{busy?"در حال ثبت...":"ثبت و نهایی کردن فروش"}</button>{marginBlocked&&<small className="checkout-blocked">قیمت زیر Margin Guard است.</small>}{missingReasons.length>0&&<small className="checkout-blocked">برای Override قیمت دلیل وارد کن.</small>}{officialBlocked&&<small className="checkout-blocked">اطلاعات هویتی فروشنده برای فاکتور رسمی کامل نیست.</small>}<small className="checkout-note">مانده پرداخت‌نشده مستقیماً به حساب مشتری منتقل می‌شود.</small></aside></div></>
}
