"use client";
import {useCallback,useEffect,useState} from "react";
import {useAuth} from "@/components/auth-provider";
import {createEdgePairing,getEdgeDevices,revokeEdgeDevice} from "@/lib/api";
import type {EdgeDevice,EdgePairing} from "@/lib/types";
import {getStoreEdgeStatus,triggerStoreEdgeSync,type StoreEdgeStatus,STORE_EDGE_URL} from "@/lib/edge";

const EDGE_INSTALLER_URL=process.env.NEXT_PUBLIC_EDGE_INSTALLER_URL||"";

export default function StoreEdgePage(){
  const {session}=useAuth();
  const [devices,setDevices]=useState<EdgeDevice[]>([]);const[pairing,setPairing]=useState<EdgePairing|null>(null);
  const [local,setLocal]=useState<StoreEdgeStatus|null>(null);const[message,setMessage]=useState("");const[busy,setBusy]=useState(false);
  const load=useCallback(async()=>{if(!session)return;const [ds,ls]=await Promise.all([getEdgeDevices(session),getStoreEdgeStatus().catch(()=>null)]);setDevices(ds);setLocal(ls)},[session]);
  useEffect(()=>{void load()},[load]);
  async function makePair(){if(!session)return;setBusy(true);setMessage("");try{setPairing(await createEdgePairing(session));}catch(e){setMessage(e instanceof Error?e.message:"کد اتصال ساخته نشد") }finally{setBusy(false)}}
  async function revoke(id:string){if(!session||!confirm("دسترسی این Store Edge قطع شود؟ فروش‌های محلی همگام‌نشده روی همان دستگاه باقی می‌مانند."))return;setBusy(true);try{await revokeEdgeDevice(session,id);await load()}catch(e){setMessage(e instanceof Error?e.message:"قطع دسترسی انجام نشد")}finally{setBusy(false)}}
  async function sync(){setBusy(true);setMessage("");try{await triggerStoreEdgeSync();setMessage("همگام‌سازی Store Edge انجام شد.");await load()}catch(e){setMessage(e instanceof Error?e.message:"Store Edge در دسترس نیست")}finally{setBusy(false)}}
  return <><div className="page-head"><div><span className="eyebrow">تداوم فروش</span><h1>Store Edge و فروش آفلاین</h1><p>صندوق این کامپیوتر می‌تواند هنگام قطع اینترنت فروش نقد و کارت را محلی ثبت کند و بعداً با سرور همگام شود.</p></div><a className="ghost-btn" target="_blank" rel="noreferrer" href={STORE_EDGE_URL}>باز کردن صندوق آفلاین</a></div>
  {message&&<div className="network-notice">{message}</div>}
  <section className="edge-overview-grid"><article className="panel edge-live-card"><div className="panel-head"><div><span className="panel-kicker">این دستگاه</span><h2>وضعیت Agent محلی</h2></div><span className={local?.paired?local.last_sync_error?"status-pill warn":"status-pill ok":"status-pill"}>{local?.paired?(local.last_sync_error?"آفلاین / صف محلی":"متصل و آماده"):"Agent پیدا نشد"}</span></div>{local?.paired?<div className="edge-live-stats"><div><span>دستگاه</span><b>{local.device_name||"Store Edge"}</b></div><div><span>کاتالوگ محلی</span><b>{local.catalog_items.toLocaleString("fa-IR")} کالا</b></div><div><span>در انتظار Sync</span><b>{local.pending_sales.toLocaleString("fa-IR")}</b></div><div><span>تعارض</span><b className={local.conflicts?"danger-text":""}>{local.conflicts.toLocaleString("fa-IR")}</b></div></div>:<div className="edge-install-help"><b>Store Agent روی این کامپیوتر نصب یا اجرا نشده است.</b><p>در ویندوز فقط یک‌بار Setup را نصب کن؛ از آن به بعد Agent به‌صورت Windows Service با روشن‌شدن سیستم خودکار اجرا می‌شود.</p>{EDGE_INSTALLER_URL?<a className="primary-btn edge-download-btn" href={EDGE_INSTALLER_URL}>دانلود Store Agent ویندوز</a>:<small>لینک دانلود Release هنوز برای این محیط تنظیم نشده است. مدیر سیستم باید <code>NEXT_PUBLIC_EDGE_INSTALLER_URL</code> را روی Setup امضاشده تنظیم کند.</small>}</div>}<div className="edge-actions"><button className="primary-btn" disabled={busy} onClick={()=>void sync()}>همگام‌سازی الان</button><a className="ghost-btn" href={STORE_EDGE_URL} target="_blank" rel="noreferrer">صندوق محلی</a></div></article>
  <article className="panel"><div className="panel-head"><div><span className="panel-kicker">اتصال امن</span><h2>Pair کردن کامپیوتر جدید</h2><p>کد یک‌بارمصرف ۱۰ دقیقه اعتبار دارد و secret دستگاه فقط یک‌بار به Agent تحویل می‌شود.</p></div></div>{pairing?<div className="pair-code-box"><span>کد اتصال</span><code>{pairing.pair_code}</code><small>انقضا: {new Date(pairing.expires_at).toLocaleString("fa-IR")}</small><p>این کد را در صفحه محلی Store Edge وارد کن.</p></div>:<button className="primary-btn" disabled={busy} onClick={()=>void makePair()}>ساخت کد اتصال</button>}</article></section>
  <section className="panel"><div className="panel-head"><div><span className="panel-kicker">دستگاه‌ها</span><h2>Store Edgeهای متصل</h2><p>دستگاه گم‌شده یا قدیمی را فوراً revoke کن.</p></div></div><div className="table-wrap"><table><thead><tr><th>نام دستگاه</th><th>وضعیت</th><th>آخرین ارتباط</th><th>تاریخ اتصال</th><th></th></tr></thead><tbody>{devices.length?devices.map(d=><tr key={d.id}><td><b>{d.name}</b></td><td>{d.active?<span className="status-pill ok">فعال</span>:<span className="status-pill">قطع‌شده</span>}</td><td>{d.last_seen_at?new Date(d.last_seen_at).toLocaleString("fa-IR"):"—"}</td><td>{new Date(d.created_at).toLocaleString("fa-IR")}</td><td>{d.active&&<button className="table-action danger-text" disabled={busy} onClick={()=>void revoke(d.id)}>قطع دسترسی</button>}</td></tr>):<tr><td colSpan={5}><div className="table-state">هنوز Store Edge متصل نشده است.</div></td></tr>}</tbody></table></div></section>
  <section className="edge-policy panel"><b>سیاست Offline نسخه 15.7.1</b><p>در حالت قطع اینترنت فقط فروش کامل <strong>نقد یا کارت</strong> محلی ثبت می‌شود. نسیه، پرداخت ترکیبی، رزرو شبکه و تأمین همکار همچنان آنلاین هستند. اگر هنگام Sync موجودی سرور با فروش فیزیکی تعارض داشته باشد، سند محلی حذف نمی‌شود و وارد صف «نیاز به بررسی» می‌شود.</p></section></>;
}
